#! /bin/bash
set -Eeuo pipefail
source globals

! check_command ffmpeg && exit 3

function print_usage() {
  echo "Usage: add-cover -a|--audio <audio file> -c|--cover <cover image>"
}

KEEP=false

OPTIONS=ha:c:k
LONGOPTIONS=help,audio:,cover:,keep
PARSED=$(getopt -o ${OPTIONS} --long ${LONGOPTIONS} -n "$0" -- "$@")
eval set -- "$PARSED"

while [ $# -ge 1 ]; do
  case "$1" in
    -a|--audio)
      AUDIO="${2}"
      AUDIO_FORMAT=$(ffprobe -v error -show_format "${AUDIO}" | \
                     sed -n "s/^format_name=\(.*\)/\1/p")
      shift 2
      ;;
    -c|--cover)
      COVER="${2}"
      shift 2
      ;;
    -k|--keep)
      KEEP=true
      shift
      ;;
    -h|--help)
      print_usage
      exit
      ;;
    --)
      shift
      break
      ;;
    *)
      show_error "Error"
      exit 3
      ;;
  esac
done

TMP="$(mktemp)"
trap 'rm -f "${TMP}"' INT TERM EXIT ERR

if [[ -v COVER ]] || [[ -v AUDIO ]]; then
  ffmpeg -i "${AUDIO}" -i "${COVER}" \
    -map_metadata 0 -map_chapters 0 -map 0 -map 1:0 \
    -c copy -f "${AUDIO_FORMAT}" -y "${TMP}"
  if "${KEEP}"; then
    mv "${AUDIO}" "${AUDIO}.bak"
  fi
  mv "${TMP}" "${AUDIO}"
  sync
else
  show_error "ERROR: missing parameters"
  print_usage
  exit 3
fi
