#! /bin/bash
set -eu
source globals

item=""
flag=0

addSong () {
  item=$(ask_question "What's the song's name?")
  if [ -z "${item}" ]; then exit; fi
  check=$(ask_question "So the name is \"${item}\"? [Y/n]")
  if [[ $check =~ ^([nN][oO]|[nN])$ ]]; then
    echo "No problem. Let's try again."
    addSong
  fi
}

addArtist () {
  item=$(ask_question "Who made it?")
  if [ -z "${item}" ]; then exit; fi
  check=$(ask_question "So it's by \"${item}\"? [Y/n]")
  if [[ $check =~ ^([nN][oO]|[nN])$ ]]; then
    echo "No problem. Let's try again."
    addArtist
  fi
}

if [ -f "$HOME/.files/music2add" ]; then
  echo "Okay, so..."
else
  mkdir -p "$HOME/.files"
  touch "$HOME/.files/music2add"
  echo "Okay, new files, so..."
fi

addSong
song=${item}
addArtist
artist=${item}

IFS_BACKUP=$IFS
IFS=$'\t'
while read -r tune maker
do
  [ "$tune" == "Song" ] && [ "$maker" == "Artist" ] && continue
  if [ "$song" == "$tune" ] && [ "$maker" == "$artist" ]; then
    flag=1
    break
  fi
done < "$HOME/.files/music2add"
IFS=$IFS_BACKUP

if [ ${flag} -eq 0 ]; then
  printf "%s\t%s" "$song" "$artist" >> "$HOME/.files/music2add"
  show_success "Done!"
  exit
else
  show_success "Already there! No changed needed."
  exit
fi
