#! /bin/bash
set -eu
source globals

function hardcode_cleanup {
  sed -i "s/\(\x92\|\x91\)/'/g" "${1}"
  sed -i "s/\(\x94\|\x93\)/\"/g" "${1}"
}

NAME=${1%.*}
EXTENSION=${1##*.}
OUTPUT="subbed_video.${EXTENSION}"

if [ -f "${NAME}.srt" ]; then
  ENCODING=$(file -i "$NAME.srt" | sed -n "s/.*charset=\(.*\)$/\1/p")
  SUBEXTENSION="srt"
  if ! [[ "${ENCODING}" = "utf-8" ]]; then
    hardcode_cleanup "${NAME}.srt"
    ENCODING=$(file -i "$NAME.srt" | sed -n "s/.*charset=\(.*\)$/\1/p")
  fi
  if ! [[ "${ENCODING}" = "utf-8" ]]; then
    show_info "Converting ${NAME}.srt ENCODING from ${ENCODING} to utf-8."
    iconv -f "${ENCODING}" -t "utf-8" "${NAME}.srt" > temp.srt && \
      mv temp.srt "${NAME}.srt"
  fi
elif [ -f "${NAME}.ass" ]; then
  ENCODING=$(file -i "$NAME.ass" | sed -n "s/.*charset=\(.*\)$/\1/p")
  SUBEXTENSION="ass"
  if ! [[ "${ENCODING}" = "utf-8" ]]; then
    hardcode_cleanup "${NAME}.ass"
    ENCODING=$(file -i "$NAME.ass" | sed -n "s/.*charset=\(.*\)$/\1/p")
  fi
  if ! [[ "${ENCODING}" = "utf-8" ]]; then
    show_info "Converting ${NAME}.ass ENCODING from ${ENCODING} to utf-8."
    iconv -f "${ENCODING}" -t "utf-8" "${NAME}.ass" > temp.ass && \
      mv temp.ass "${NAME}.ass"
  fi
else
  show_error "No subtitle file detected."
  exit 3
fi


case ${EXTENSION} in
  avi)
    OUTPUT="subbed_video.mp4"
    EXTENSION="mp4"
    ffmpeg -i "${1}" -sub_charenc UTF-8 -i "${NAME}.${SUBEXTENSION}" \
      -c:v copy -c:a copy -c:s mov_text \
      -metadata:s:s:0 language=eng -metadata:s:s:0 handler="English" \
      -id3v2_version 3 -write_id3v1 1 \
      "${OUTPUT}"
    ;;
  mp4|m4v)
    ffmpeg -i "${1}" -sub_charenc UTF-8 -i "${NAME}.${SUBEXTENSION}" \
      -c:v copy -c:a copy -c:s mov_text \
      -metadata:s:s:0 language=eng -metadata:s:s:0 handler="English" \
      -id3v2_version 3 -write_id3v1 1 \
      "${OUTPUT}"
    ;;
  mkv)
    ffmpeg -i "${1}" -sub_charenc UTF-8 -i "${NAME}.${SUBEXTENSION}" \
      -c:v copy -c:a copy -c:s srt \
      -metadata:s:s:0 language=eng -metadata:s:s:0 handler="English" \
      -id3v2_version 3 -write_id3v1 1 \
      "${OUTPUT}"
    ;;
  *)
    show_error "${EXTENSION} files are not supported."
    exit 3
esac

mv "${1}" "${1}.bak"
mv "${NAME}.${SUBEXTENSION}" "${NAME}.${SUBEXTENSION}.bak"
mv "${OUTPUT}" "${NAME}.${EXTENSION}"
