#! /bin/bash
set -eu
source globals

function hardcode_cleanup {
  sed -i "s/\(\x92\|\x91\)/'/g" "${1}"
  sed -i "s/\(\x94\|\x93\)/\"/g" "${1}"
}

name=${1%.*}
extension=${1##*.}
encoding=$(file -i "$name.srt" | sed -n "s/.*charset=\(.*\)$/\1/p")
output="subbed_video.${extension}"

if [ -f "${name}.srt" ]; then
  encoding=$(file -i "$name.srt" | sed -n "s/.*charset=\(.*\)$/\1/p")
  subextension="srt"
  if ! [[ "${encoding}" = "utf-8" ]]; then
    hardcode_cleanup "${name}.srt"
    encoding=$(file -i "$name.srt" | sed -n "s/.*charset=\(.*\)$/\1/p")
  fi
  if ! [[ "${encoding}" = "utf-8" ]]; then
    show_info "Converting ${name}.srt encoding from ${encoding} to utf-8."
    iconv -f "${encoding}" -t "utf-8" "${name}.srt" > temp.srt && \
      mv temp.srt "${name}.srt"
  fi
elif [ -f "${name}.ass" ]; then
  encoding=$(file -i "$name.srt" | sed -n "s/.*charset=\(.*\)$/\1/p")
  subextension="ass"
  if ! [[ "${encoding}" = "utf-8" ]]; then
    hardcode_cleanup "${name}.srt"
    encoding=$(file -i "$name.srt" | sed -n "s/.*charset=\(.*\)$/\1/p")
  fi
  if ! [[ "${encoding}" = "utf-8" ]]; then
    show_info "Converting ${name}.ass encoding from ${encoding} to utf-8."
    iconv -f "${encoding}" -t "utf-8" "${name}.ass" > temp.ass && \
      mv temp.ass "${name}.ass"
  fi
else
  show_error "No subtitle file detected."
  exit 3
fi


case ${extension} in
  avi)
    output="subbed_video.mp4"
    ffmpeg -i "${1}" -sub_charenc UTF-8 -i "${name}.${subextension}" \
      -c:v copy -c:a copy -c:s mov_text \
      -metadata:s:s:0 language=eng -metadata:s:s:0 handler="English" \
      -id3v2_version 3 -write_id3v1 1 \
      "${output}"
    ;;
  mp4)
    ffmpeg -i "${1}" -sub_charenc UTF-8 -i "${name}.${subextension}" \
      -c:v copy -c:a copy -c:s mov_text \
      -metadata:s:s:0 language=eng -metadata:s:s:0 handler="English" \
      -id3v2_version 3 -write_id3v1 1 \
      "${output}"
    ;;
  m4v)
    ffmpeg -i "${1}" -sub_charenc UTF-8 -i "${name}.${subextension}" \
      -c:v copy -c:a copy -c:s mov_text \
      -metadata:s:s:0 language=eng -metadata:s:s:0 handler="English" \
      -id3v2_version 3 -write_id3v1 1 \
      "${output}"
    ;;
  mkv)
    ffmpeg -i "${1}" -sub_charenc UTF-8 -i "${name}.${subextension}" \
      -c:v copy -c:a copy -c:s srt \
      -metadata:s:s:0 language=eng -metadata:s:s:0 handler="English" \
      -id3v2_version 3 -write_id3v1 1 \
      "${output}"
    ;;
  *)
    show_error "${extension} files are not supported."
    exit 3
esac

mv "${1}" "${1}.bak"
mv "${name}.${subextension}" "${name}.${subextension}.bak"
mv "${output}" "${1}"
