#! /bin/bash
set -eu
source globals

! check_command ffmpeg && exit 3

function print_usage() {
  echo "Usage: add-cover -a|--audio <audio file> -c|--cover <cover image>"
}

OPTIONS=ha:c:
LONGOPTIONS=help,audio:,cover:
PARSED=$(getopt -o ${OPTIONS} --long ${LONGOPTIONS} -n "$0" -- "$@")
eval set -- "$PARSED"

while [ $# -ge 1 ]; do
  case "$1" in
    -a|--audio)
      export AUDIO="${2}"
      shift 2
      ;;
    -c|--cover)
      export COVER="${2}"
      shift 2
      ;;
    -h|--help)
      print_usage
      exit
      ;;
    --)
      shift
      break
      ;;
    *)
      show_error "Error"
      exit 3
      ;;
  esac
done

TMP="$(mktemp)"

if [[ -v COVER ]] || [[ -v AUDIO ]]; then
  ffmpeg -i "${COVER}" -i "${AUDIO}" -map 0:0 -map 1:0 -c copy "${TMP}"
  mv "${TMP}" "${AUDIO}"
else
  show_error "ERROR: missing parameters"
  print_usage
  exit 3
fi
