#! /bin/bash
set -eu
source globals

SONG=
ARTIST=
FLAG=0

addSong () {
  local check
  SONG=$(ask_question "What's the song's name?")
  if [ -z "${SONG}" ]; then exit; fi

  check=$(ask_question "So the name is \"${SONG}\"? [Y/n]")
  while [[ $check =~ ^([nN][oO]|[nN])$ ]]; do
    echo "No problem. Let's try again."
    check=$(ask_question "So the name is \"${SONG}\"? [Y/n]")
  done
}

addArtist () {
  local check
  ARTIST=$(ask_question "Who made it?")
  if [ -z "${ARTIST}" ]; then exit; fi

  check=$(ask_question "So it's by \"${ARTIST}\"? [Y/n]")
  while [[ $check =~ ^([nN][oO]|[nN])$ ]]; do
    echo "No problem. Let's try again."
    check=$(ask_question "So it's by \"${ARTIST}\"? [Y/n]")
  done
}

if [ -f "$HOME/.files/music2add" ]; then
  echo "Okay, so..."
else
  mkdir -p "$HOME/.files"
  touch "$HOME/.files/music2add"
  echo "Okay, new files, so..."
fi

addSong
addArtist

IFS_BACKUP=$IFS
IFS=$'\t'
while read -r TUNE MAKER
do
  [ "$TUNE" == "Song" ] && [ "$MAKER" == "Artist" ] && continue
  if [ "$SONG" == "$TUNE" ] && [ "$MAKER" == "$ARTIST" ]; then
    FLAG=1
    break
  fi
done < "$HOME/.files/music2add"
IFS=$IFS_BACKUP

if [ ${FLAG} -eq 0 ]; then
  printf "%s\t%s" "$SONG" "$ARTIST" >> "$HOME/.files/music2add"
  show_success "Done!"
  exit
else
  show_success "Already there! No changed needed."
  exit
fi
