#! /bin/bash
set -eu
source globals

item=""
flag=0

addSong () {
  read -p "What's the song's name? " -a item
  if [ -z $item ]; then exit; fi
  read -p "So the name is \"${item[*]}\"? [Y/n] " check
  if [[ $check =~ ^([yY][eE][sS]|[yY])$ ]]; then
    return
  elif [[ $check =~ ^([nN][oO]|[nN])$ ]]; then
    echo "No problem. Let's try again."
    addSong
  else
    exit
  fi
}

addArtist () {
  read -p "Who made it?  " -a item
  if [ -z $item ]; then exit; fi
  read -p "So it's by \"${item[*]}\"? [Y/n] " check
  if [[ $check =~ ^([yY][eE][sS]|[yY])$ ]]; then
    return
  elif [[ $check =~ ^([nN][oO]|[nN])$ ]]; then
    echo "No problem. Let's try again."
    addArtist
  else
    exit
  fi
}

if [ -f $HOME/.files/music2add ]; then
  echo "Okay, so..."
else
  mkdir -p $HOME/.files
  touch $HOME/.files/music2add
  echo "Okay, new files, so..."
fi

addSong
song=${item}
addArtist
artist=${item}

IFS_BACKUP=$IFS
IFS=$'\t'
while read tune maker
do
  [ $tune == "Song" ] && [ $maker == "Artist" ] && continue
  if [ $song == $tune ] && [ $maker == $artist ]; then
    flag=1
    break
  fi
done < $HOME/.files/music2add
IFS=$IFS_BACKUP

if [ ${flag} -eq 0 ]; then
  echo $song$'\t'$'\t'$artist >> $HOME/.files/music2add
  show_success "Done!"
  exit
else
  show_success "Already there! No changed needed."
  exit
fi
