#! /bin/bash
set -Eeuo pipefail

ROOT="$(dirname "${0}")"

source "${ROOT}"/globals

function print_usage {
  show_header "Usage: alphabetize"
  show_listitem "\
  -b|--backup   back up the original file (default: false)
  -r|--reverse  reverse output (default: false)
  -h|--help     print (this) error message"
}

OPTIONS=bhr
LONGOPTIONS=backup,help,reverse
PARSED=$(getopt -o ${OPTIONS} --long ${LONGOPTIONS} -n "${0}" -- "${@}")
eval set -- "${PARSED}"

ISBACKUP=false
REVERSE=false
while [ ${#} -ge 1 ]; do
  case "${1}" in
    -b | --backup)
      ISBACKUP=true
      shift 1
      ;;
    -h | --help)
      print_usage
      exit
      ;;
    -r | --reverse)
      REVERSE=true
      shift
      ;;
    --)
      shift
      break
      ;;
    *)
      show_error "Error"
      exit 3
      ;;
  esac
done

if [ -t 0 ]; then
  if ! [ -e "${1}" ]; then
    show_error "ERROR: ${1@Q} does not exist."
    exit 3
  fi

  TMP="$(mktemp)"
  trap 'rm -f "${TMP}"; exit' INT TERM ERR EXIT

  if "${REVERSE}"; then
    sort -f -u -r "${1}" > "${TMP}"
  else
    sort -f -u "${1}" > "${TMP}"
  fi

  if "${ISBACKUP}"; then
    mv "${1}" "${1}.bak"
  fi

  mv "${TMP}" "${1}"
else
  if "${REVERSE}"; then
    cat | sort -f -u -r
  else
    cat | sort -f -u
  fi
fi
