#! /bin/bash
set -Eeu
source globals

OPTIONS=b
LONGOPTIONS=backup
PARSED=$(getopt -o ${OPTIONS} --long ${LONGOPTIONS} -n "$0" -- "$@")
eval set -- "$PARSED"

ISBACKUP=false
while [ $# -ge 1 ]; do
  case "$1" in
    -b|--backup)
      ISBACKUP=true
      shift 1
      ;;
    --)
      shift
      break
      ;;
    *)
      show_error "Error"
      exit 3
      ;;
  esac
done

if ! [ -e "${1}" ]; then
  show_error "ERROR: ${1} does not exist."
  exit 2
fi

TMP="$(mktemp)"
trap 'rm -f "${TMP}"; exit' INT TERM ERR EXIT

sort -d -f -u "${1}" > "${TMP}"
if "${ISBACKUP}"; then
  mv "${1}" "${1}.bak"
fi
mv "${TMP}" "${1}"
