#! /bin/bash
set -Eeuo pipefail

ROOT="$(dirname "${0}")"

source "${ROOT}"/globals

function print_usage {
  show_header "Usage: alphabetize"
  show_listitem "  -b|--backup  (optional) save the original file"
  show_listitem "  -h|--help    print (this) error message"
}

OPTIONS=bh
LONGOPTIONS=backup,help
PARSED=$(getopt -o ${OPTIONS} --long ${LONGOPTIONS} -n "${0}" -- "${@}")
eval set -- "${PARSED}"

ISBACKUP=false
while [ ${#} -ge 1 ]; do
  case "${1}" in
    -b | --backup)
      ISBACKUP=true
      shift 1
      ;;
    -h | --help)
      print_usage
      exit
      ;;
    --)
      shift
      break
      ;;
    *)
      show_error "Error"
      exit 3
      ;;
  esac
done

if [ -t 0 ]; then
  if ! [ -e "${1}" ]; then
    show_error "ERROR: ${1@Q} does not exist."
    exit 3
  fi

  TMP="$(mktemp)"
  trap 'rm -f "${TMP}"; exit' INT TERM ERR EXIT

  sort -f -u "${1}" > "${TMP}"

  if "${ISBACKUP}"; then
    mv "${1}" "${1}.bak"
  fi

  mv "${TMP}" "${1}"
else
  cat | sort -f -u
fi
