#! /bin/bash
set -eu

SOURCE=${HOME}
DEST=/run/media/quetzal/Aves/Images

# When changing these variables, be careful about specifying "dirname/" vs
# "dirname".
KVMDIR=${HOME}/.local/libvirt/images
VBOXDIR=${HOME}/.VirtualBox

if ! [ -d ${DEST} ]; then
  echo "Backup destination ${DEST} does not exist."
  exit 1
fi

sudo bash -c "\
  rsync -Pradog --sparse ${KVMDIR}/ ${DEST}/KVM/ && \
  rsync -Pradog ${VBOXDIR}/ ${DEST}/VirtualBox/"
sync
