#! /bin/bash
set -eu
source globals


#
# Backup home directory to Aves
#

if ! [ -d ${backup1} ]; then
  show_error "Backup destination ${backup1} does not exist."
  exit 1
fi

# Check if any encfs directories are decrypted.
if [ "$(grep encfs /etc/mtab)" ]; then
  show_warning "Encrypt and unmount $(grep encfs /etc/mtab | cut -d" " -f2) first."
  exit 1
fi

show_info "Syncing ${HOME} to Aves."
sudo rsync -Pradog \
  --delete-excluded ${HOME}/ ${backup1}/${USER^}/ \
  --exclude '.VirtualBox/*' --exclude '.local/libvirt/images/*'
sync
show_success "Done." && echo


#
# Backup Aves to Avian
#

if [ -d ${backup2} ]; then
  show_info "Syncing Aves to Avian."
  sudo rsync -Pradog \
    --delete-excluded ${backup1}/ ${backup2}/ \
    --exclude 'Images/KVM/*'
  sync
  show_success "Done." && echo
fi
