#! /bin/bash
set -eu

SOURCE=${HOME}/
DEST=/run/media/quetzal/Aves/Quetzal/

if ! [ -d ${DEST} ]; then
  echo "Backup destination ${DEST} does not exist."
  exit 1
fi

sudo rsync -Pradog \
  --delete-excluded ${SOURCE} ${DEST} \
  --exclude '.VirtualBox/*' --exclude '.local/libvirt/images/*'
sync
