#! /bin/bash
set -eu

SOURCE=${HOME}/
DEST=/run/media/quetzal/Aves/Quetzal/

# When changing these variables, be careful about specifying "dirname/" vs
# "dirname".
KVMDIR=${HOME}/.local/libvirt/images
VBOXDIR=${HOME}/.VirtualBox

if ! [ -d ${DEST} ]; then
  echo "Backup destination ${DEST} does not exist."
  exit 1
fi

# Check if any encfs directories are decrypted.
if [ "$(grep encfs /etc/mtab)" ]; then
  echo "Encrypt and unmount $(grep encfs /etc/mtab | cut -d" " -f2) first."
  exit 1
fi

sudo rsync -Pradog \
  --delete-excluded ${SOURCE} ${DEST} \
  --exclude "${VBOXDIR}/*" --exclude "${KVMDIR}/*"
sync
