#! /bin/bash
set -e

if ! [ -d /run/media/quetzal/Aves ]; then
  echo "Backup not mounted."
  exit 1
fi

sudo bash -c "\
  rsync -Pradog --sparse \
    /home/quetzal/.local/libvirt/images/ \
    /run/media/quetzal/Aves/Images/KVM/ && \
  rsync -Pradog \
    /home/quetzal/.VirtualBox/ \
    /run/media/quetzal/Aves/Images/VirtualBox/"
sync
