#! /bin/bash
set -eu

SOURCE=${HOME}
DEST=/run/media/quetzal/Aves/Images

if ! [ -d ${DEST} ]; then
  echo "Backup destination ${DEST} does not exist."
  exit 1
fi

sudo bash -c "\
  rsync -Pradog --sparse \
    ${SOURCE}/.local/libvirt/images/ \
    ${DEST}/KVM/ && \
  rsync -Pradog \
    ${SOURCE}/.VirtualBox/ \
    ${DEST}/VirtualBox/"
sync
