#!/bin/bash

# SPDX-FileCopyrightText: 2017 - 2024 sudorook <daemon@nullcodon.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.

set -eu

#
# Globals
#

if ! command -v notify-send > /dev/null; then
  exit 3
fi

# Thresholds
LOW=40
FULL=80
CRITICAL=10

# Icons
LOW_ICON=battery-low
FULL_ICON=battery-full-charging
CRITICAL_ICON=battery-caution

# Notification flags
LOW_FLAG_SENT=false
FULL_FLAG_SENT=false
CRITICAL_FLAG_SENT=false

BATTERY_PATH=/sys/class/power_supply/BAT0
DISPLAY=:0
LOCKFILE=/tmp/battery-notify.lock

# Exit if lockfile already set by running battery-notify instance.
if [ -e "${LOCKFILE}" ] && kill -0 "$(< "${LOCKFILE}")"; then
  exit
fi

trap 'rm -f ${LOCKFILE}; exit' INT TERM ERR EXIT
echo $$ > ${LOCKFILE}

while true; do
  if [ -e ${BATTERY_PATH} ]; then
    STATE=$(< ${BATTERY_PATH}/status)
    LEVEL=$(< ${BATTERY_PATH}/capacity)

    if [ "${STATE}" == "Discharging" ]; then
      # Send flag when battery drops below critical threshold.
      if [ "${LEVEL}" -le "${CRITICAL}" ]; then
        if ! ${CRITICAL_FLAG_SENT}; then
          notify-send -u critical -i ${CRITICAL_ICON} \
            "Battery critical" \
            "Battery is at ${LEVEL}%. Plug in the power supply now."
          CRITICAL_FLAG_SENT=true
        fi
      # If battery level is above critical, check if it is below the low
      # threshold and send flag if so.
      elif [ "${LEVEL}" -le "${LOW}" ]; then
        if ! "${LOW_FLAG_SENT}"; then
          notify-send -u critical -i ${LOW_ICON} \
            "Battery low" \
            "Battery is at ${LEVEL}%. Plug in the power supply soon."
          LOW_FLAG_SENT=true
        fi
      fi

      # Unset the full battery flag while discharging.
      FULL_FLAG_SENT=false
    fi

    if [ "${STATE}" == "Charging" ]; then
      # Send flag when battery is full (i.e. above the full battery threshold).
      if [ "${LEVEL}" -gt "${FULL}" ]; then
        # Check if the full battery message has been sent already. If not, send
        # it out.
        if ! ${FULL_FLAG_SENT}; then
          notify-send -u critical -i ${FULL_ICON} \
            "Battery full" \
            "Battery is at ${LEVEL}%. Unplug the power supply."
          FULL_FLAG_SENT=true
        fi
      fi

      # Unset critical battery flag if charging, and unset the low flag if the
      # battery level is above the critical threshold.
      CRITICAL_FLAG_SENT=false
      if [ "${LEVEL}" -gt "${CRITICAL}" ]; then
        LOW_FLAG_SENT=false
      fi
    fi
  fi
  sleep 120s
done
