#! /bin/bash
set -eu

low_battery=40
full_battery=80
critical_battery=10
low_icon=battery-low
full_icon=battery-full-charging
critical_icon=battery-caution
low_flag_sent=false
full_flag_sent=false
critical_flag_sent=false

battery_path=/sys/class/power_supply/BAT0
display=:0

lockfile=/tmp/battery-notify.lock

if [ -e "${lockfile}" ] && kill -0 "$(cat "${lockfile}")"; then
  exit
fi

trap 'rm -f ${lockfile}; exit' INT TERM EXIT
echo $$ > ${lockfile}

while true; do
  if [ -e ${battery_path} ]; then
    battery_state=$(<${battery_path}/status)
    battery_level=$(<${battery_path}/capacity)

    if [ "${battery_state}" == "Discharging" ]; then
      # Send flag when battery drops below critical threshold.
      if [ "${battery_level}" -le "${critical_battery}" ]; then
        if ! ${critical_flag_sent}; then
          DISPLAY=${display} notify-send -u critical -i ${critical_icon} \
            "Battery critical" \
            "Battery is at ${battery_level}%. Plug in the power supply now."
          critical_flag_sent=true
        fi
      # If battery level is above critical, check if it is below the low
      # threshold and send flag if so.
      elif [ "${battery_level}" -le "${low_battery}" ]; then
        if ! "${low_flag_sent}"; then
          DISPLAY=${display} notify-send -u critical -i ${low_icon} \
            "Battery low" \
            "Battery is at ${battery_level}%. Plug in the power supply soon."
          low_flag_sent=true
        fi
      fi

      # Unset the full battery flag while discharging.
      full_flag_sent=false
    fi

    if [ "${battery_state}" == "Charging" ]; then
      # Send flag when battery is full (i.e. above the full battery threshold).
      if [ "${battery_level}" -gt "${full_battery}" ]; then
        # Check if the full battery message has been sent already. If not, send
        # it out.
        if ! ${full_flag_sent}; then
          DISPLAY=${display} notify-send -u critical -i ${full_icon} \
            "Battery full" \
            "Battery is at ${battery_level}%. Unplug the power supply."
          full_flag_sent=true
        fi
      fi

      # Unset critical battery flag if charging, and unset the low flag if the
      # battery level is above the critical threshold.
      critical_flag_sent=false
      if [ "${battery_level}" -gt "${critical_battery}" ]; then
        low_flag_sent=false
      fi
    fi
  fi
  sleep 120s
done
