#! /bin/bash
set -euo pipefail

ROOT="$(dirname "${0}")"

source "${ROOT}"/globals

! check_command jq sed && exit 3

function delete_directory() {
  local dir="${1}"
  local dir_owner
  if [ -d "${dir}" ]; then
    dir_owner="$(stat -c "%U" "${dir}")"
    if [[ "${USER}" = "${dir_owner}" ]]; then
      if [[ -v 2 ]]; then
        show_info "${2}"
      fi
      rm -rf "${dir}"
      sync
    else
      show_warning "${dir@Q} owned by ${dir_owner@Q}. Skipping."
    fi
  fi
}

function delete_file() {
  local file="${1}"
  local file_owner
  if [ -f "${file}" ]; then
    file_owner="$(stat -c "%U" "${file}")"
    if [[ "${USER}" = "${file_owner}" ]]; then
      if [[ -v 2 ]]; then
        show_info "${2}"
      fi
      rm -f "${file}"
      sync
    else
      show_warning "${file@Q} owned by ${file_owner@Q}. Skipping."
    fi
  fi
}

function delete_config_section() {
  local file="${1}"
  local file_owner
  local header="${2}"
  local tmp
  if [ -f "${file}" ]; then
    file_owner="$(stat -c "%U" "${file}")"
    if [[ "${USER}" = "${file_owner}" ]]; then
      if [[ -v 3 ]]; then
        show_info "${3}"
      fi
      tmp="$(mktemp)"
      sed "/\[${header}\]/,/^\s*$/{d}" "${file}" | sed '${/^$/d}' > "${tmp}"
      mv "${tmp}" "${file}"
      sync
    else
      show_warning "${file@Q} owned by ${file_owner@Q}. Skipping."
    fi
  fi
}

function delete_json_section() {
  local file="${1}"
  local file_owner
  local path="${2}"
  local tmp
  if [ -f "${file}" ]; then
    file_owner="$(stat -c "%U" "${file}")"
    if [[ "${USER}" = "${file_owner}" ]]; then
      if [[ -v 3 ]]; then
        show_info "${3}"
      fi
      tmp="$(mktemp)"
      # Check if file end with newline. If it does not, then use '-j'.
      if [ "$(tail -n 1 "${file}" | wc -l)" -eq 0 ]; then
        jq -j "${path} = []" "${file}" > "${tmp}"
      else
        jq "${path} = []" "${file}" > "${tmp}"
      fi
      mv "${tmp}" "${file}"
      sync
    else
      show_warning "${file@Q} owned by ${file_owner@Q}. Skipping."
    fi
  fi
}

# KDE Clipboard
if check_command qdbus 2> /dev/null; then
  if qdbus > /dev/null 2>&1; then
    show_info "Clearing Klipper history."
    qdbus org.kde.klipper /klipper org.kde.klipper.klipper.clearClipboardHistory
  fi
fi

# Nvim state
delete_directory \
  "${HOME}/.local/state/nvim" \
  "Clearing Neovim state."

# Vim undo
delete_directory \
  "${HOME}/.vim/undo" \
  "Clearing Vim undo history."

# Recent files, etc.
if check_command sweeper 2> /dev/null; then
  if [ -v DESKTOP_SESSION ]; then
    show_info "Running sweeper."
    sweeper --automatic 2> /dev/null
  fi
fi

# System-wide cleanup
if check_command bleachbit 2> /dev/null; then
  if [ -f "${HOME}/.config/bleachbit/bleachbit.ini" ]; then
    show_info "Running BleachBit (${USER})."
    bleachbit -c --preset
  else
    show_warning "BleachBit not configured. Skipping."
  fi
fi

# Ark history
if [ -f "${HOME}"/.local/share/ark/ark_recentfiles ]; then
  show_info "Clearing Ark history."
  cat > "${HOME}"/.local/share/ark/ark_recentfiles << EOF
[RecentFiles]
files\size=0
EOF
fi

# Okular recent files.
delete_directory \
  "${HOME}/.local/share/okular/docdata" \
  "Deleting Okular document data."
delete_config_section \
  "${HOME}/.config/okularrc" \
  "Clearing Okular recent file history."

# Gwenview image viewer history.
delete_directory \
  "${HOME}/.local/share/gwenview/recentfolders" \
  "Deleting Gwenview folder history."
delete_config_section \
  "${HOME}/.config/gwenviewrc" \
  "Clearing Gwenview recent file history."

# Calibre
delete_directory \
  "${HOME}/Documents/Library/.caltrash/" \
  "Emptying Calibre trash."
delete_json_section \
  "${HOME}/.config/calibre/viewer-webengine.json" \
  ".session_data.standalone_recently_opened" \
  "Clearing ebook-viewer history."

# Remove trash directory
delete_directory \
  "${HOME}/.local/share/Trash/" \
  "Deleting trash directory."

# Trash at Share/ mountpoint
delete_directory \
  "${HOME}/Share/.Trash-1000" \
  "Deleting ~/Share trash directory."

# Python history
delete_file \
  "${HOME}/.python_history" \
  "Deleting Python REPL history."

# Node REPL history
delete_file \
  "${HOME}"/.node_repl_history \
  "Deleting node REPL history."

# mpv watch_later
delete_directory \
  "${HOME}/.local/state/mpv/watch_later" \
  "Clearing mpv history."

# less history
delete_file \
  "${HOME}/.local/state/lesshst" \
  "Deleting less history."

# wget history
delete_file \
  "${HOME}/.wget-hsts" \
  "Deleting wget history."
