#! /bin/bash
set -eu
source globals

function delete_directory() {
  local dir_owner
  if [ -d "${1}" ]; then
    dir_owner="$(stat -c "%U" "${1}")"
    if [[ "${USER}" = "${dir_owner}" ]]; then
      if [[ -v 2 ]]; then
        show_header "${2}"
      fi
      rm -rvf "${1}"
      echo
    fi
  fi
}

# KDE Clipboard
if check_command qdbus; then
  if qdbus >/dev/null 2>&1; then
    show_header "Clearing Klipper history."
    echo qdbus org.kde.klipper /klipper org.kde.klipper.klipper.clearClipboardHistory
  fi
else
  echo
fi

# Nvim undo
delete_directory \
  "${HOME}/.local/state/nvim/undo" \
  "Clearing Neovim undo history."

# Vim undo
delete_directory \
  "${HOME}/.vim/undo" \
  "Clearing Vim undo history."

# Recent files, etc.
if check_command sweeper; then
  if [ -v DESKTOP_SESSION ]; then
    show_header "Running sweeper."
    echo sweeper --automatic
  fi
else
  echo
fi

# System-wide cleanup
if check_command bleachbit; then
  show_header "Running BleachBit (user)."
  bleachbit -c --preset

  show_header "Running BleachBit (root)."
  sudo bleachbit -c --preset
else
  echo
fi

# Calibre trash
delete_directory \
  "${HOME}/Documents/Library/.caltrash/" \
  "Emptying Calibre trash."
