#! /bin/bash
set -euo pipefail

ROOT="$(dirname "${0}")"

source "${ROOT}"/globals

function print_usage() {
  show_header "Usage: copy-playlist"
  show_listitem "  -i|--input <m3u file>"
  show_listitem "  -d|--dest <destination directory>"
  show_listitem "  -m|--music <music directory>"
}

OPTIONS=hi:d:m:
LONGOPTIONS=help,input:,dest:,music:
PARSED=$(getopt -o "${OPTIONS}" --long "${LONGOPTIONS}" -n "${0}" -- "${@}")
eval set -- "${PARSED}"

while [ ${#} -ge 1 ]; do
  case "${1}" in
    -i | --input)
      INPUT=${2}
      shift 2
      ;;
    -d | --dest)
      DEST=${2}
      shift 2
      ;;
    -m | --music)
      MUSIC=${2}
      shift 2
      ;;
    -h | --help)
      print_usage
      exit
      ;;
    --)
      shift
      break
      ;;
    *)
      show_error "ERROR"
      print_usage
      exit 3
      ;;
  esac
done

MUSIC="${MUSIC:-"${musicdir}"}"

if ! [ -d "${MUSIC}" ]; then
  show_error "ERROR: ${MUSIC@Q} does not exist. Exiting."
  exit 3
fi

if [[ -v INPUT ]] && [[ -v DEST ]]; then
  mkdir -p "${DEST}"
  if ! [ -f "${INPUT}" ]; then
    show_error "ERROR: ${INPUT@Q} not a file. Exiting."
    exit 3
  fi
  shopt -s extglob
  while read -r ITEM; do
    if [ -f "${MUSIC}/${ITEM}" ]; then
      cp -uav "${MUSIC}/${ITEM}" "${DEST}/${ITEM##*/+([[:digit:]]) }"
      sync
    else
      show_error "ERROR: file ${ITEM@Q} not found. Exiting."
      exit 3
    fi
  done < "${INPUT}"
  shopt -u extglob
else
  show_error "ERROR: Improper usage."
  print_usage
  exit 3
fi
