#! /bin/bash
set -euo pipefail
source globals

function print_usage() {
  echo "Usage:"
  echo "  copy-playlist -i|--input <m3u file> \\"
  echo "                -d|--dest <destination directory> \\"
  echo "                -m|--music <music directory>"
}

OPTIONS=hi:d:m:
LONGOPTIONS=help,input:,dest:,music:
PARSED=$(getopt -o ${OPTIONS} --long ${LONGOPTIONS} -n "$0" -- "$@")
eval set -- "$PARSED"

while [ $# -ge 1 ]; do
  case "$1" in
    -i|--input)
      export INPUT=${2}
      shift 2
      ;;
    -d|--dest)
      export DEST=${2}
      shift 2
      ;;
    -m|--music)
      export MUSIC=${2}
      shift 2
      ;;
    -h|--help)
      print_usage
      exit
      ;;
    --)
      shift
      break
      ;;
    *)
      show_error "ERROR"
      print_usage
      exit 3
      ;;
  esac
done

if ! [[ -v MUSIC ]]; then
  if [[ -v musicdir ]] && [ -d "${musicdir}" ]; then
    MUSIC="${musicdir}"
  fi
fi

if [[ -v INPUT ]] && [[ -v DEST ]]; then
  mkdir -p "${DEST}"
  if [ -f "${INPUT}" ]; then
    while read -r file; do
      newfile="$(echo "${file}" | \
                 sed -e "s,\(.*\)/\(.*\)/[0-9]\+ \(.*\.mp3\)$,\3,g")"
      cp -u -v "${MUSIC}/${file}" -d "${DEST}/${newfile}"
    done < "${INPUT}"
    sync
  fi
else
  show_error "Try again."
fi
