#! /bin/bash
set -Eeuo pipefail

ROOT="$(dirname "${0}")"

source "${ROOT}"/globals

! check_command ffmpeg ffprobe sed && exit 3

function print_usage() {
  show_header "Usage: add-cover -c|--cover <image> <file>"
}

function get_format() {
  ffprobe -v error -show_format file:"${AUDIO}" |
    sed -n "s/^format_name=\(.*\)/\1/p"
}

KEEP=false

OPTIONS=hc:k
LONGOPTIONS=help,cover:,keep
PARSED=$(getopt -o "${OPTIONS}" --long "${LONGOPTIONS}" -n "${0}" -- "${@}")
eval set -- "${PARSED}"

while [ ${#} -ge 1 ]; do
  case "${1}" in
    -c | --cover)
      COVER="${2}"
      shift 2
      ;;
    -k | --keep)
      KEEP=true
      shift
      ;;
    -h | --help)
      print_usage
      exit
      ;;
    --)
      shift
      break
      ;;
    *)
      show_error "Error"
      exit 3
      ;;
  esac
done

TMP="$(mktemp)"
trap 'rm -f "${TMP}"' INT TERM EXIT ERR

if ! [[ -v COVER ]] && ! [[ -f "${COVER}" ]]; then
  show_error "ERROR: no cover specified. Exiting."
  exit 3
fi

if [ "${#}" -eq 1 ] && [ -f "${1}" ]; then
  AUDIO="${1}"
else
  show_error "ERROR: missing input file. Exiting."
  print_usage
  exit 3
fi

ffmpeg -i file:"${AUDIO}" -i file:"${COVER}" \
  -map_metadata 0 -map_chapters 0 -map 0 -map 1:0 \
  -c copy -f "$(get_format)" -y "${TMP}"
if "${KEEP}"; then
  mv "${AUDIO}" "${AUDIO}_$(date +%Y%m%d-%H%M%S).bak"
fi
mv "${TMP}" "${AUDIO}"
sync
