#! /bin/bash
set -eu

encryptpath=${HOME}/.encrypted
decryptpath=${HOME}/.decrypted

mkdir -p ${encryptpath}
mkdir -p ${decryptpath}

encfs ${encryptpath} ${decryptpath}

echo "Decrypted successfully."
cd ${decryptpath}
