#! /bin/bash
set -eu

source globals


show_warning "Encfs does not provide robust security."

mkdir -p ${encryptpath}
mkdir -p ${decryptpath}

encfs ${encryptpath} ${decryptpath}
echo "Decrypted successfully."
