#! /bin/bash
set -eu

WARNING="\033[1;33m"
NC='\033[0m'

encryptpath=${HOME}/.encrypted
decryptpath=${HOME}/.decrypted

mkdir -p ${encryptpath}
mkdir -p ${decryptpath}

echo -e "${WARNING}Encfs does not provide robust security.${NC}"

encfs ${encryptpath} ${decryptpath}

echo "Decrypted successfully."
