#! /bin/bash
set -eu
source globals

files="-name *.sw[a-p] -o -name *.bak -o -name *~"

if [ $# = 0 ]; then
  find . \( ${files} \)
  find . \( ${files} \) -exec rm -rf {} +
else
  find ${@} \( ${files} \)
  find ${@} \( ${files} \) -exec rm -rf {} +
fi
