#! /bin/bash
set -eu

ROOT="$(dirname "${0}")"

source "${ROOT}"/globals

! check_command encfs && exit 3

function set_icon {
  if check_command gio; then
    gio set "${DECRYPTPATH}" -t string metadata::custom-icon-name folder-unlocked
  fi
  if check_command kwriteconfig5; then
    kwriteconfig5 --file "${DECRYPTPATH}" --group 'Desktop Entry' --key 'Icon' 'folder-unlocked'
  fi
}

function unset_icon {
  if check_command gio; then
    gio set "${DECRYPTPATH}" -t unset metadata::custom-icon-name
  fi
  if check_command kwriteconfig5; then
    kwriteconfig5 --file "${DECRYPTPATH}" --group 'Desktop Entry' --key 'Icon' --delete
  fi
}

show_warning "Encfs does not provide robust security. Don't use it."

ENCRYPTPATH="${encryptpath:-${HOME}/.encrypted}"
DECRYPTPATH="${decryptpath:-${HOME}/.decrypted}"

mkdir -p "${ENCRYPTPATH}"
mkdir -p "${DECRYPTPATH}"

if grep "${DECRYPTPATH}" /etc/mtab > /dev/null 2>&1; then
  set_icon
  show_info "${DECRYPTPATH} is already decrypted."
  exit
fi

encfs "${ENCRYPTPATH}" "${DECRYPTPATH}"

if grep "${DECRYPTPATH}" /etc/mtab > /dev/null 2>&1; then
  set_icon
  show_success "Decrypted successfully."
else
  unset_icon
  show_error "Decryption failed."
  exit 3
fi
