#! /bin/bash
set -eu
source globals

! check_command encfs gio && exit 3

show_warning "Encfs does not provide robust security. Don't use it."

ENCRYPTPATH="${encryptpath:-${HOME}/.encrypted}"
DECRYPTPATH="${decryptpath:-${HOME}/.decrypted}"

mkdir -p "${ENCRYPTPATH}"
mkdir -p "${DECRYPTPATH}"

if grep "${DECRYPTPATH}" /etc/mtab > /dev/null 2>&1; then
  gio set "${DECRYPTPATH}" -t string metadata::custom-icon-name folder-unlocked
  show_info "${DECRYPTPATH} is already decrypted."
  exit
fi

encfs "${ENCRYPTPATH}" "${DECRYPTPATH}"

if grep "${DECRYPTPATH}" /etc/mtab > /dev/null 2>&1; then
  gio set "${DECRYPTPATH}" -t string metadata::custom-icon-name folder-unlocked
  show_success "Decrypted successfully."
else
  gio set "${DECRYPTPATH}" -t unset metadata::custom-icon-name
  show_error "Decryption failed."
  exit 3
fi
