#! /bin/bash
set -eu

WARNING="\033[1;33m"
NC='\033[0m'

encryptpath=${HOME}/.encrypted
decryptpath=${HOME}/.decrypted

echo -e "${WARNING}Encfs does not provide robust security.${NC}"

mkdir -p ${encryptpath}
mkdir -p ${decryptpath}

fusermount -u ${decryptpath}
echo "Encrypted successfully."
