#! /bin/bash
set -eu
source globals

show_warning "Encfs does not provide robust security."

mkdir -p ${encryptpath}
mkdir -p ${decryptpath}

fusermount -u ${decryptpath}
if [ $? -eq 0 ]; then
  gio set ${decryptpath} -t string metadata::custom-icon-name folder-locked
  show_success "Encrypted successfully."
else
  gio set ${decryptpath} -t string metadata::custom-icon-name folder-locked
  show_success "Encryption failed."
fi
