#! /bin/bash
set -eu

ROOT="$(dirname "${0}")"

source "${ROOT}"/globals

! check_command ebook-convert && exit 3

for ITEM in "${@}"; do
  if [ -f "${ITEM}" ]; then
    NAME="${ITEM%%.*}"
    EXT="${ITEM##*.}"
    case "${EXT,,}" in
      azw3 | mobi | lit)
        ebook-convert "${ITEM}" "${NAME}.epub" --change-justification "left"
        ;;
      *)
        show_warning "${ITEM@Q} not supported. Skipping..."
        ;;
    esac
    unset NAME
    unset EXT
  fi
done
