#! /bin/bash
set -euo pipefail
source globals

! check_command sed zip unzip && exit 3

#
# Functions
#

# Add read and write permissions to CSS files
function set_rw {
  find . -type f -iname "*.css" -exec chmod u+w,+r {} \;
}

# Remove justified text
function unjustify {
  find . -type f -iname "*.css" -exec sed -i \
    -e "s,text-align\s*:\s*justify;,/*text-align: justify;*/,g" \
    -e "s,text-align\s*:\s*justify !important;,/*text-align: justify !important;*/,g" \
    -e "s,text-align\s*:\s*justify[\n\r]*$,/*text-align: justify*/,g" \
    -e "s,text-align\s*:\s*justify},/*text-align: justify*/},g" {} \;
}

# Remove hard-coded colors
function unset_colors {
  find . -type f -iname "*.css" -exec sed -i \
    -e "s,background-color\ *:\ *#\([[:xdigit:]]\+\);,/*background-color: \1;*/,g" \
    -e "s,background-color\ *:\ *#\([[:xdigit:]]\+\)$,/*background-color: \1*/,g" \
    -e "s,background-color\ *:\ *#\([[:xdigit:]]\+\)},/*background-color: \1*/},g" \
    -e "s,background-color\ *:\ *\(rgba([\d[[:digit:]]\,\ ]\+)\);,/*background-color: \1;*/,g" \
    -e "s,background-color\ *:\ *\(rgba([\d[[:digit:]]\,\ ]\+)\)$,/*background-color: \1*/,g" \
    -e "s,background-color\ *:\ *\(rgba([\d[[:digit:]]\,\ ]\+)\)},/*background-color: \1*/},g" \
    -e "s,\(;*\ *\)color\ *:\ *#\([[:xdigit:]]\+\);,\1/*color: \2;*/,g" \
    -e "s,\(;*\ *\)color\ *:\ *#\([[:xdigit:]]\+\)$,\1/*color: \2*/,g" \
    -e "s,\(;*\ *\)color\ *:\ *#\([[:xdigit:]]\+\)},\1/*color: \2*/},g" {} \;
}

# Check if file is ePub
function is_epub {
  local in="${1}"
  local ext="${1##*.}"
  local mime
  mime="$(file -b --mime-type "${in}")"
  if [[ "${mime}" =~ epub ]] || [[ "${ext,,}" = epub ]]; then
    return 0
  else
    return 1
  fi
}

function print_usage {
  show_header "Usage: epub-fixup -c|--unset_color <input>"
  show_listitem "  -c  (optional) comment out hard-coded colors"
  show_listitem "  -h  print (this) help message"
}


#
# Main
#

UNSETCOLOR=false

OPTIONS=ch
LONGOPTIONS=unset_color,help
PARSED=$(getopt -o ${OPTIONS} --long ${LONGOPTIONS} -n "${0}" -- "${@}")
eval set -- "${PARSED}"

while [ "${#}" -ge 1 ]; do
  case "${1}" in
    -c|--unset_color)
      UNSETCOLOR=true
      shift 1
      ;;
    -h|--help)
      print_usage
      exit
      ;;
    --)
      shift
      break
      ;;
    *)
      show_error "ERROR: invalid flag."
      print_usage
      exit 3
      ;;
  esac
done

if ! is_epub "${1}"; then
  show_error "ERROR: Input not ePub format."
  exit 3
fi

FILE="$(basename "${1}")"
NAME="${1%.*}"
EXTENSION="${1##*.}"

BUILDDIR="$(mktemp -d)"
trap 'rm -rf "${BUILDDIR}"; exit' INT TERM ERR EXIT

cp "${1}" "${BUILDDIR}"
pushd "${BUILDDIR}" >/dev/null

unzip "${FILE}"

set_rw
unjustify
if ${UNSETCOLOR}; then
  unset_colors
fi

zip -u "${FILE}" || true # override return false if no update performed

popd >/dev/null
mv "${BUILDDIR}/${FILE}" "${NAME} new.${EXTENSION}"
