#! /bin/bash
set -euo pipefail
source globals

! check_command zip unzip && exit 3

# Removed justified text
function unjustify {
  find . -type f -name "*.css" \
    -exec sed -i "s,text-align\s*:\s*justify;,/*text-align: justify;*/,g" {} \; \
    -exec sed -i "s,text-align\s*:\s*justify[\n\r]*$,/*text-align: justify*/,g" {} \; \
    -exec sed -i "s,text-align\s*:\s*justify},/*text-align: justify*/},g" {} \;
}

FILE="$(basename "${1}")"
NAME="${1%.*}"
EXTENSION="${1##*.}"

if ! [[ "$(file -b --mime-type "${1}")" =~ epub ]]; then
  if ! [[ "${EXTENSION,,}" = epub ]]; then
    show_error "ERROR: Input not EPUB format."
    exit 3
  fi
fi

BUILDDIR="$(mktemp -d)"
trap 'rm -rf "${BUILDDIR}"; exit' INT TERM ERR EXIT

cp "${1}" "${BUILDDIR}"
pushd "${BUILDDIR}" >/dev/null

unzip "${FILE}"

unjustify

zip -u "${FILE}"

popd >/dev/null
mv "${BUILDDIR}/${FILE}" "${NAME} new.${EXTENSION}"
