#! /bin/bash
set -eu
source globals

! check_command ebook-convert && exit 3

for ITEM in "${@}"; do
  if [ -f "${ITEM}" ]; then
    case "${ITEM##*.}" in
      AZW3 | MOBI | LIT | azw3 | mobi | lit)
        ebook-convert "${ITEM}" "${ITEM%%.*}.epub" --change-justification "left"
        ;;
      *)
        show_warning "${ITEM@Q} not supported. Skipping..."
        ;;
    esac
  fi
done
