#! /bin/bash
set -euo pipefail
source globals

! check_command ffmpeg ffprobe && exit 3

NAME=${1%.*}
EXTENSION=${1##*.}
STREAMS=()
TITLES=()
FORMATS=()

function parse_streams {
  local stream
  local title
  local format
  while IFS=$'\n' read -r line; do
    stream="$(echo "${line}" | sed -n "s/^ \+Stream #\([0-9]\+:[0-9]\+\)(\?\([a-z]\+\)\?)\?: Subtitle: \([a-z\_]\+\)\(, [0-9]\+x[0-9]\+\)\?\( (default)\)\?\( (forced)\)\?/\1/p")"
    title="$(echo "${line}" | sed -n "s/^ \+Stream #\([0-9]\+:[0-9]\+\)(\?\([a-z]\+\)\?)\?: Subtitle: \([a-z\_]\+\)\(, [0-9]\+x[0-9]\+\)\?\( (default)\)\?\( (forced)\)\?/\2/p")"
    format="$(echo "${line}" | sed -n "s/^ \+Stream #\([0-9]\+:[0-9]\+\)(\?\([a-z]\+\)\?)\?: Subtitle: \([a-z\_]\+\)\(, [0-9]\+x[0-9]\+\)\?\( (default)\)\?\( (forced)\)\?/\3/p")"

    if ! [[ "${stream}" = "" ]]; then
      STREAMS+=("${stream}")
      if [ -z "${title}" ]; then
        title=eng
      fi
      TITLES+=("${title}")
      FORMATS+=("${format}")
    fi
  done <<< "$(ffprobe "${NAME}.${EXTENSION}" 2>&1 | grep "^ \+Stream.*: Subtitle")"
}

function extract_streams {
  local cmd
  for i in $(seq 0 $(( ${#TITLES[@]} - 1))); do
    cmd="ffmpeg -i '${NAME}.${EXTENSION}' -map ${STREAMS[${i}]} -c copy"
    case "${FORMATS[${i}]}" in
      ass)
        cmd+=" '${NAME}_${STREAMS[${i}]}_${TITLES[${i}]}.ass'"
        ;;
      dvd_subtitle)
        if [[ "${EXTENSION}" = mp4 ]]; then
          cmd+=" '${NAME}_${STREAMS[${i}]}_${TITLES[${i}]}.mp4'"
        else
          cmd+=" '${NAME}_${STREAMS[${i}]}_${TITLES[${i}]}.mkv'"
        fi
        ;;
      mov_text|srt|subrip)
        cmd+=" '${NAME}_${STREAMS[${i}]}_${TITLES[${i}]}.srt'"
        ;;
      hdmv_pgs_subtitle)
        cmd+=" '${NAME}_${STREAMS[${i}]}_${TITLES[${i}]}.sup'"
        ;;
      *)
        show_warning "Format ${FORMATS[${i}]} not supported. Skipping."
        continue
        ;;
    esac
    eval "${cmd}"
  done
}

parse_streams
if [ ${#STREAMS[@]} = 0 ]; then
  show_error "ERROR: No subtitle streams found in ${1}. Exiting."
  exit 3
fi

extract_streams
