#! /bin/bash
set -eu
source globals

NAME=${1%.*}
EXTENSION=${1##*.}
case ${EXTENSION} in
  webm)
    ffmpeg -i "${1}" -y "${NAME}.mp3"
    ;;
  mp4|mkv)
    ffmpeg -i "${1}" -c:a libmp3lame -y "${NAME}.mp3"
    ;;
  *)
    show_error "ERROR: '${1}' is not compatible"
    exit 1
    ;;
esac
