#!/usr/bin/env python3

# SPDX-FileCopyrightText: 2018 - 2024 sudorook <daemon@nullcodon.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.

"""
Generate a list of playlists from all the artists available in the Beets database.
"""

import os
import yaml
import beets.library

BEETSCONFIG = "~/.config/beets/config.yaml"
BEETSDB = "~/.config/beets/library.db"


def generate_playlists():
    """Generate list of playlists from all albumartists in the Beets database."""
    # Load the Beets library.
    libpath = os.path.expanduser(BEETSDB)
    lib = beets.library.Library(libpath)

    # Get a list of artists.
    artists = set()
    for album in lib.albums():
        artists.add(album.albumartist)
    artists = list(artists)

    # Generate a list of playlists from the artists in the Beets database.
    playlists = []
    playlists.append({"name": "All Songs.m3u", "query": ""})
    playlists.append({"name": "Top Rated.m3u", "query": "rating:5"})
    for artist in artists:
        playlists.append(
            {
                "name": "Best of " + artist + ".m3u",
                "query": 'albumartist:"' + artist + '" rating:5',
            }
        )
    return playlists


def write_playlists(p):
    """Write list of playlists to the Beets YAML config file."""
    # Load the YAML config file.
    configpath = os.path.expanduser(BEETSCONFIG)
    with open(configpath, encoding="UTF-8") as f:
        data = yaml.safe_load(f)

    # Write playlists to the beets YAML config file.
    data["smartplaylist"]["playlists"] = p
    with open(configpath, "w", encoding="UTF-8") as f:
        yaml.dump(data, f, default_flow_style=False)


def main():
    playlists = generate_playlists()
    write_playlists(playlists)


if __name__ == "__main__":
    main()
