#! /usr/bin/env python
"""
Generate a list of playlists from all the artists available in the Beets
database.
"""

import os
import yaml
import beets.library

# Load the YAML config file.
configpath = os.path.expanduser('~/.config/beets/config.yaml')
with open(configpath) as f:
    data = yaml.safe_load(f)

# Load the Beets library.
libpath = os.path.expanduser('~/.config/beets/library.db')
lib = beets.library.Library(libpath)

# Get a list of artists.
artists = set()
for album in lib.albums():
    artists.add(album.albumartist)
artists = list(artists)

# Generate a list of playlists from the artists in the Beets database.
playlists = []
playlists.append({'name': 'All Songs.m3u', 'query': ''})
playlists.append({'name': 'Top Rated.m3u', 'query': 'rating:5'})
for artist in artists:
    playlists.append({'name': 'Best of ' + artist + '.m3u', 'query': 'artist:"' + artist + '" rating:5'})

# Write playlists to the beets YAML config file.
data['smartplaylist']['playlists'] = playlists
with open(configpath, 'w') as f:
    yaml.dump(data, f, default_flow_style=False)
