#! /bin/bash
set -eu
source globals

! check_command youtube-dl mid3v2 && exit 3

OPTIONS=t:a:u:f:
LONGOPTIONS=title:,artist:,url:,format
PARSED=$(getopt -o ${OPTIONS} --long ${LONGOPTIONS} -n "$0" -- "$@")
eval set -- "${PARSED}"

while [ $# -ge 1 ]; do
  case "$1" in
    -t|--title)
      TITLE="$2"
      shift 2
      ;;
    -a|--artist)
      ARTIST="$2"
      shift 2
      ;;
    -u|--url)
      URL="$2"
      shift 2
      ;;
    -f|--format)
      FORMAT="$2"
      shift 2
      ;;
    --)
      shift
      break
      ;;
    *)
      show_error "Error: unknown command line option \"$2\"."
      exit 3
      ;;
  esac
done

# Prompt for inputs if they were not already specified on the command line.
if ! [[ -v TITLE ]]; then TITLE=$(ask_question "What is the title?"); fi
if ! [[ -v ARTIST ]]; then ARTIST=$(ask_question "Who is the artist?"); fi
if ! [[ -v URL ]]; then URL=$(ask_question "What is the URL?"); fi
if ! [[ -v FORMAT ]]; then FORMAT=mp3; fi

# Download the file, extract audio, and set the ID3v2 tags.
youtube-dl --extract-audio --prefer-ffmpeg --audio-format ${FORMAT} \
  "${URL//\"}" -o "${TITLE} - ${ARTIST}.%(ext)s"
mid3v2 "${TITLE} - ${ARTIST}.${FORMAT}" -a "${ARTIST}" -t "${TITLE}"
