#!/bin/bash

# SPDX-FileCopyrightText: 2018 - 2024 sudorook <daemon@nullcodon.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.

set -eu

ROOT="$(dirname "${0}")"

source "${ROOT}"/globals

YTDL=yt-dlp

! check_command "${YTDL}" mid3v2 && exit 3

function print_usage {
  show_header "Usage: get-song"
  show_listitem "  -t|--title   <song title>"
  show_listitem "  -a|--artist  <name of band / recording artist / etc>"
  show_listitem "  -u|--url     <url for download>"
  show_listitem "  -f|--format  <audio format (e.g. mp3, opus)>"
  show_listitem "  -h|--help    print (this) help message"
}

OPTIONS=t:a:u:f:h
LONGOPTIONS=title:,artist:,url:,format,help
PARSED=$(getopt -o "${OPTIONS}" --long "${LONGOPTIONS}" -n "${0}" -- "${@}")
eval set -- "${PARSED}"

while [ ${#} -ge 1 ]; do
  case "${1}" in
    -t | --title)
      TITLE="${2}"
      shift 2
      ;;
    -a | --artist)
      ARTIST="${2}"
      shift 2
      ;;
    -u | --url)
      URL="${2}"
      shift 2
      ;;
    -f | --format)
      FORMAT="${2}"
      shift 2
      ;;
    -h | --help)
      print_usage
      exit
      ;;
    --)
      shift
      break
      ;;
    *)
      show_error "ERROR: unknown command line option ${2@Q}."
      exit 3
      ;;
  esac
done

# Prompt for inputs if they were not already specified on the command line.
TITLE="${TITLE:-"$(ask_question "What is the title?")"}"
ARTIST="${ARTIST:-"$(ask_question "Who is the artist?")"}"
URL="${URL:-"$(ask_question "What is the URL?")"}"
FORMAT="${FORMAT:-mp3}"

# Download the file, extract audio, and set the ID3v2 tags.
"${YTDL}" "${URL//\"/}" \
  --extract-audio \
  --prefer-ffmpeg \
  --audio-format "${FORMAT}" \
  --ignore-config \
  -o "${TITLE} - ${ARTIST}.%(ext)s"
mid3v2 "${TITLE} - ${ARTIST}.${FORMAT}" -a "${ARTIST}" -t "${TITLE}"
