#!/bin/bash

# SPDX-FileCopyrightText: 2022 - 2023 sudorook <daemon@nullcodon.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.

set -eu

ROOT="$(dirname "${0}")"

source "${ROOT}"/globals

! check_command git && exit 3

function head_count {
  git rev-list --since="${UNTIL}" --count --all
}

if [ "${#}" -eq 0 ]; then
  UNTIL="$(date -d now +%s)"
else
  UNTIL="$(date -d "${*}" +%s)"
fi

COUNT="$(head_count)"
BRANCH="$(git branch --show-current)"

if [ -n "${COUNT}" ] && [ "${COUNT}" -gt 0 ]; then
  git push origin HEAD~"${COUNT}":"${BRANCH}"
else
  git push origin "${BRANCH}"
fi
