#! /bin/bash
set -eu

ROOT="$(dirname "${0}")"

source "${ROOT}"/globals

IN="${1:-.}"
if ! DIR="$(git -C "${IN}" rev-parse --show-toplevel 2> /dev/null)"; then
  show_error "ERROR: ${IN@Q} is not a Git directory. Exiting."
  exit 3
fi

pushd "${DIR}" > /dev/null

git reflog expire --expire=now --expire-unreachable=now --rewrite --all
git gc --prune=now --aggressive
git submodule foreach git gc --prune=now --aggressive
git fsck

popd > /dev/null
