#!/bin/bash

# SPDX-FileCopyrightText: 2023 - 2024 sudorook <daemon@nullcodon.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.

set -eu

ROOT="$(dirname "${0}")"

source "${ROOT}"/globals

! check_command git && exit 3

IN="${1:-.}"
if ! DIR="$(git -C "${IN}" rev-parse --show-toplevel 2> /dev/null)"; then
  show_error "ERROR: ${IN@Q} is not a Git directory. Exiting."
  exit 3
fi

pushd "${DIR}" > /dev/null

git reflog expire --expire=now --expire-unreachable=now --rewrite --all
git gc --prune=now --aggressive
git submodule foreach git reflog expire --expire=now --expire-unreachable=now --rewrite --all
git submodule foreach git gc --prune=now --aggressive
git fsck

popd > /dev/null
