#! /bin/bash

#
# Utility functions
#

show_error() {
  local red=$'\033[1;31m'
  local nc=$'\033[0m'
  echo -e "${red}${*}${nc}" 1>&2
}
export -f show_error

show_info() {
  local green=$'\033[1;32m'
  local nc=$'\033[0m'
  echo -n "${green}$*${nc}"
}
export -f show_info

show_warning() {
  local yellow=$'\033[1;33m'
  local nc=$'\033[0m'
  echo -e "${yellow}$*${nc}"
}
export -f show_warning

show_question() {
  local blue=$'\033[1;34m'
  local nc=$'\033[0m'
  echo -e "${blue}$*${nc}"
}
export -f show_question

ask_question() {
  local blue=$'\033[1;34m'
  local nc=$'\033[0m'
  local var
  read -r -p "${blue}$*${nc} " var
  echo "${var}"
}
export -f ask_question

ask_secret() {
  local blue=$'\033[1;34m'
  local nc=$'\033[0m'
  local var
  stty -echo echonl
  read -r -p "${blue}$*${nc} " var
  stty echo -echonl
  echo "${var}"
}
export -f ask_secret

show_success() {
  local purple=$'\033[1;35m'
  local nc=$'\033[0m'
  echo -e "${purple}$*${nc}"
}
export -f show_success

show_header() {
  local cyan=$'\033[1;36m'
  local nc=$'\033[0m'
  echo -e "${cyan}$*${nc}"
}
export -f show_header

show_listitem() {
  local white=$'\033[1;37m'
  local nc=$'\033[0m'
  echo -e "${white}$*${nc}"
}
export -f show_listitem

check_command() {
  local package
  local missing=()
  for package in "${@}"; do
    if ! command -v "${package}" > /dev/null; then
      missing+=("${package}")
    fi
  done
  if [ ${#missing[@]} -eq 0 ]; then
    return 0
  else
    show_error "MISSING: ${missing[*]@Q} not installed."
    return 1
  fi
}
export -f check_command

#
# Global variables
#

# archive destination dir
archivedir=
export archivedir

# backup-home, backup-vms
backup1=
backup2=
export backup1
export backup2

# kvm dirs
kvmdir=
kvmshare=
export kvmdir
export kvmshare

# virtualbox dirs
vboxdir=
export vboxdir

# encrypted folder
encryptpath=
decryptpath=
export encryptpath
export decryptpath

# theme dirs
gtkdir=
plasmadir=
icondir=
export gtkdir
export plasmadir
export icondir

# thunderbird theme
thunderbirddir=
export thunderbirddir

# zsh dir
zshdir=
export zshdir

# pkgbuild dir
pkgbuilddir=
export pkgbuilddir

# project folders
projectdir=
ignoreprojectdirs=()
export projectdir
export ignoreprojectdirs

# music folders
musicdir=
export musicdir

# video folders
videodir=
export videodir

# Calibre folders
calibrelibrarydir=
export calibrelibrarydir

# Zotero folders
zoterodatadir=
export zoterodatadir

# entry
entrydir=
template=
export entrydir
export template
