#! /bin/bash

#
# Utility functions
#

show_error() {
  echo -e $'\033[1;31m'"$*"$'\033[0m' 1>&2
}
export -f show_error
show_info() {
  echo -e $'\033[1;32m'"$*"$'\033[0m'
}
export -f show_info
show_warning() {
  echo -e $'\033[1;33m'"$*"$'\033[0m'
}
export -f show_warning
show_question() {
  echo -e $'\033[1;34m'"$*"$'\033[0m'
}
export -f show_question
ask_question() {
  local var
  read -r -p $'\033[1;34m'"$* "$'\033[0m' var
  echo "${var}"
}
export -f ask_question
ask_secret() {
  local var
  stty -echo echonl
  read -r -p $'\033[1;34m'"$* "$'\033[0m' var
  stty echo -echonl
  echo "${var}"
}
export -f ask_secret
show_success() {
  echo -e $'\033[1;35m'"$*"$'\033[0m'
}
export -f show_success
show_header() {
  echo -e $'\033[1;36m'"$*"$'\033[0m'
}
export -f show_header
show_listitem() {
  echo -e $'\033[1;37m'"$*"$'\033[0m'
}
export -f show_listitem

check_command() {
  local package
  local missing=()
  for package in "${@}"; do
    if ! command -v "${package}" > /dev/null; then
      missing+=("${package}")
    fi
  done
  if [ ${#missing[@]} -eq 0 ]; then
    return 0
  else
    show_error "MISSING: ${missing[*]@Q} not installed."
    return 1
  fi
}
export -f check_command

#
# Global variables
#

# archive destination dir
archivedir=
export archivedir

# backup-home, backup-vms
backup1=
backup2=
export backup1
export backup2

# kvm dirs
kvmdir=
kvmshare=
export kvmdir
export kvmshare

# virtualbox dirs
vboxdir=
export vboxdir

# encrypted folder
encryptpath=
decryptpath=
export encryptpath
export decryptpath

# theme dirs
gtkdir=
plasmadir=
icondir=
export gtkdir
export plasmadir
export icondir

# thunderbird theme
thunderbirddir=
export thunderbirddir

# zsh dir
zshdir=
export zshdir

# pkgbuild dir
pkgbuilddir=
export pkgbuilddir

# project folders
projectdir=
ignoreprojectdirs=()
export projectdir
export ignoreprojectdirs

# music folders
musicdir=
export musicdir

# video folders
videodir=
export videodir

# Calibre folders
calibrelibrarydir=
export calibrelibrarydir

# Zotero folders
zoterodatadir=
export zoterodatadir

# entry
entrydir=
template=
export entrydir
export template
