#! /bin/bash
set -eu
source globals

#
# Functions
#

# Check if all files passed to script are mp4s.
function is_all_mp4s() {
  for file in "${@}"; do
    echo "$file"
    if ! [ "${file##*.}" = "mp4" ]; then
      return 1
    fi
  done
  return 0
}

# Check if all files passed to script are mkvs.
function is_all_mkvs() {
  for file in "${@}"; do
    echo "$file"
    if ! [ "${file##*.}" = "mp4" ]; then
      return 1
    fi
  done
  return 0
}

# Join mp4s by converting them to a transport stream (ts), concatenating the
# streams, and converting the result back to an mp4.
function join_mp4s() {
  local name
  local extension
  local input="concat:"
  local idx=0
  for file in "${@}"; do
    if [ "${file}" = "${OUTFILE}" ]; then
      continue
    fi
    name=${file%.*}
    extension=${file##*.}
    ffmpeg -i "${file}" -c copy -bsf:v h264_mp4toannexb -f h264 "${name}.ts"
    input="${input}${name}.ts|"
  done
  input=${input::-1}

  rm -f "${OUTFILE}"
  ffmpeg -i "${input}" -codec copy -bsf:a aac_adtstoasc "${OUTFILE}"

  for file in "${@}"; do
    name=${file%.*}
    rm -f "${name}.ts"
  done
}

# Join mkvs by using a concatenation file.
function join_mkvs() {
  local concatfile="concat.txt"
  local idx=0
  for file in "${@}"; do
    if [ "${file}" = "${OUTFILE}" ]; then
      continue
    fi
    echo "file '${file}'" >> "${concatfile}"
  done

  rm -f "${OUTFILE}"
  ffmpeg -f concat -i "${concatfile}" -codec copy output.mkv

  rm -f "${concatfile}"
}

# Join videos with mixed codecs using ffmpeg concat filter.
function join_mixed() {
  local input=""
  local filter=""
  local idx=0
  local cmd
  for file in "${@}"; do
    if [ "${file}" = "${OUTFILE}" ]; then
      continue
    fi
    input="${input}-i ${file@Q} "
    filter="${filter}[${idx}:v:0] [${idx}:a:0] "
    idx=$(( idx + 1 ))
  done
  filter="${filter}concat=n=${#}:v=1:a=1 [v] [a]"

  rm -f "${OUTFILE}"
  cmd=$(echo ffmpeg "${input}" -filter_complex \"${filter}\" \
             -map \"[v]\" -map \"[a]\" "${OPTIONS}" "${OUTFILE}")
  eval "${cmd}"
}


#
# Globals
#

OUTFILE=output.mp4
OPTIONS=""


#
# Main
#

# When all provided files are mp4s, use lossless concatenation by transcoding
# mp4s to mpeg transport stream (ts) files.
if is_all_mp4s "${@}"; then
  show_header "Joining MP4s."
  join_mp4s "${@}"

# When all provided files are mkvs, create a concat file with the filenames and
# use the -f concat option for ffmpeg.
elif is_all_mkvs "${@}"; then
  show_header "Joining MKVs."
  join_mkvs "${@}"

# # If multiple codes are present, use the ffmpeg concat filter.
# else
#   show_header "Joining mixed codecs."
#   join_mixed "${@}"
# fi

# If multiple codecs are present, convert non-mp4 files to mp4s and then join
# them.
else
  show_header "Converting mixed codecs to mp4 and then joining them."
  mp4s=()
  temp=()
  for file in "${@}"; do
    if [ "${file}" = "${OUTFILE}" ]; then
      continue
    fi
    name=${file%.*}
    extension=${file##*.}
    if [ "${extension}" = "mp4" ]; then
      mp4s+=("$file")
    else
      ffmpeg -i "${file}" "${name}.mp4"
      mp4s+=("${name}.mp4")
      temp+=("${name}.mp4")
    fi
  done
  join_mp4s "${mp4s[@]}"

  for f in "${temp[@]}"; do
    rm "$f"
  done
fi
