#! /bin/bash
set -eu

ROOT="$(dirname "${0}")"

source "${ROOT}"/globals

! check_command find && exit 3

KVMSHARE="${kvmshare:-${HOME}/.local/libvirt/share}"
mkdir -p "${KVMSHARE}"
find "${KVMSHARE}" -maxdepth 1 ! -path "${KVMSHARE}" -print -exec rm -rf -- '{}' +
