#!/bin/bash

# SPDX-FileCopyrightText: 2021 - 2024 sudorook <daemon@nullcodon.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.

set -euo pipefail

ROOT="$(dirname "${0}")"

source "${ROOT}"/globals

! check_command sed && exit 3

print_ass_fonts() {
  local line="${1}"
  local font
  local is_bold
  local is_italic
  local res

  font="$(echo "${line}" | cut -d"," -f2)"
  is_bold="$(echo "${line}" | cut -d"," -f8)"
  is_italic="$(echo "${line}" | cut -d"," -f9)"

  res="${font}"
  if ((is_bold == -1)); then
    res+=" (Bold)"
  fi
  if ((is_italic == -1)); then
    res+=" (Italic)"
  fi
  echo "${res}"
}

parse_lines() {
  local file="${1}"
  local extension="${file##*.}"
  local line
  case "${extension}" in
    ass | ssa)
      while read -r line; do
        print_ass_fonts "${line}"
      done <<< "$(sed -n "s/^Style: \(.*\)/\1/p" "${file}")"
      ;;
  esac
}

iterate_files() {
  local file
  local extension
  local line

  if [ -d "${1}" ]; then
    for file in "${1}"/*; do
      if [[ "$(file -ib "${file}")" =~ text/plain ]]; then
        parse_lines "${file}"
      fi
    done
  elif [ -f "${1}" ]; then
    if [[ "$(file -ib "${1}")" =~ text/plain ]]; then
      parse_lines "${1}"
    fi
  fi
}

iterate_files "${@}" | sort -u
