#! /bin/bash
set -eu

ROOT="$(dirname "${0}")"

source "${ROOT}"/globals

! check_command entr make && exit 3

if ! [ -f "${1:-./Makefile}" ]; then
  show_error "Makefile not found. Exiting."
  exit 3
fi

find "${1:-.}" -type f | entr -s "make -j$(nproc) ${1:+-f "${1}"}"
