#! /bin/bash
set -eu

ROOT="$(dirname "${0}")"

source "${ROOT}"/globals

! check_command find entr make && exit 3

DIR="${1:-.}"

if ! [ -f ./Makefile ]; then
  show_error "ERROR: Makefile not found. Exiting."
  exit 3
fi

if ! [ -d "${DIR}" ]; then
  show_error "ERROR: ${DIR@Q} not found. Exiting."
  exit 3
fi

find "${DIR}" -type f | entr -s "make -j$(nproc)"
