#! /bin/bash
set -euo pipefail

ROOT="$(dirname "${0}")"

source "${ROOT}"/globals

! check_command ffprobe find mpv xargs && exit 3

#
# Functions
#

check_inputs() {
  local item
  for item in "${@}"; do
    if [ -L "${item}" ]; then
      item="$(readlink -f "${item}")"
    fi
    if [ -d "${item}" ] || [ -f "${item}" ]; then
      continue
    else
      return 1
    fi
  done
  return 0
}

check_duration() {
  local duration
  duration="$(ffprobe -v error \
                -show_entries stream=duration \
                -select_streams a:0 \
                -of default=noprint_wrappers=1:nk=1 file:"${1}")"
  if (("${duration%.*}" >= "${CUTOFF}")); then
    return 0
  else
    return 1
  fi
}
export -f check_duration

print_list() {
  if [[ "${CUTOFF}" = 0 ]]; then
    if [[ -v FILETYPE ]]; then
      find "${IN[@]}" -type f \
        \( -iname "*.${FILETYPE}" \) -print
    else
      find "${IN[@]}" -type f \
        \( -iname "*.aac" -o \
           -iname "*.alac" -o \
           -iname "*.flac" -o \
           -iname "*.mka" -o \
           -iname "*.mp3" -o \
           -iname "*.opus" -o \
           -iname "*.wav" \) -print
    fi
  else
    if [[ -v FILETYPE ]]; then
      find "${IN[@]}" -type f \
        \( -iname "*.${FILETYPE}" \) -print0 |
        xargs -0 -P "$(nproc)" -I{} bash -c 'check_duration "{}" && echo "{}"'
    else
      find "${IN[@]}" -type f \
        \( -iname "*.aac" -o \
           -iname "*.alac" -o \
           -iname "*.flac" -o \
           -iname "*.mka" -o \
           -iname "*.mp3" -o \
           -iname "*.opus" -o \
           -iname "*.wav" \) -print0 |
        xargs -0 -P "$(nproc)" -I{} bash -c 'check_duration "{}" && echo "{}"'
    fi
  fi
}

print_usage() {
  show_header "Usage: mpv-play"
  show_listitem "\
  -c|--cutoff   <int>       filter out files below cutoff (default: 0)
  -f|--filetype <string>    set extension keep (optional)
  -r|--replaygain <string>  replaygain mode (default: album)
  -s|--shuffle              flag shuffle streams (default: false)
  -p|--pause                start mpv as paused (default: false)
  -h|--help                 print (this) help message"
}

#
# Globals
#

CUTOFF=0
SHUFFLE=false

#
# Parse command line variables.
#

OPTIONS=sf:c:hpr:
LONGOPTIONS=shuffle,filetype:,cutoff:,help,pause,replaygain:
PARSED=$(getopt -o "${OPTIONS}" --long "${LONGOPTIONS}" -n "${0}" -- "${@}")
eval set -- "${PARSED}"

while [ "${#}" -ge 1 ]; do
  case "${1}" in
    -c | --cutoff)
      CUTOFF="${2}"
      shift 2
      ;;
    -f | --filetype)
      FILETYPE="${2}"
      shift 2
      ;;
    -s | --shuffle)
      SHUFFLE=true
      shift
      ;;
    -h | --help)
      print_usage
      exit
      ;;
    -p | --pause)
      PAUSE="--pause"
      shift
      ;;
    -r | --replaygain)
      case "${2,,}" in
        album)
          REPLAYGAIN=album
          ;;
        track)
          REPLAYGAIN=track
          ;;
        no | none | off)
          REPLAYGAIN=no
          ;;
        *)
          show_error "ERROR: replaygain options are 'track', 'album', and 'no'. See man mpv."
          exit 3
          ;;
      esac
      shift 2
      ;;
    --)
      shift
      break
      ;;
    *)
      show_error "ERROR: Unknown argument ${1@Q}. Exiting."
      exit 3
      ;;
  esac
done

#
# Main
#

IN=("${@}")
! check_inputs "${IN[@]}" && exit 3
export CUTOFF

if "${SHUFFLE}"; then
  # Don't quote ${PAUSE:-} so that when PAUSE is unset, the expression
  # evaluates to nothing instead of a file named "".
  print_list | mpv ${PAUSE:-} --shuffle --no-audio-display --replaygain="${REPLAYGAIN:-album}" --playlist=-
else
  # Don't quote ${PAUSE:-} so that when PAUSE is unset, the expression
  # evaluates to nothing instead of a file named "".
  print_list | sort -V | mpv ${PAUSE:-} --no-audio-display --replaygain="${REPLAYGAIN:-album}" --playlist=-
fi
