#! /bin/bash
set -euo pipefail
source globals

! check_command pdfinfo pdfseparate pdfunite && exit 3

OPTIONS=hji:f:l:
LONGOPTIONS=help,join,input:,FIRST:,LAST:
PARSED=$(getopt -o ${OPTIONS} --long ${LONGOPTIONS} -n "$0" -- "$@")
eval set -- "$PARSED"

while [ $# -ge 1 ]; do
  case "$1" in
    -i|--input)
      IN="$2"
      OUT="${2%.*}"
      PAGES=$(pdfinfo "$2" | grep "^Pages:" | sed -n "s/^Pages:\s*\([0-9]\+\)/\1/p")
      shift 2
      ;;
    -f|--FIRST)
      FIRST="$2"
      shift 2
      ;;
    -l|--LAST)
      LAST="$2"
      shift 2
      ;;
    -j|--join)
      JOINPDFS=true
      shift
      ;;
    -h|--help)
      echo "pdfsplit options:"
      echo "  -i|--input  <pdf input>"
      echo "  -f|--first  <# of first page to split>"
      echo "  -l|--last   <# of last page to split>"
      echo "  -j|--join   <flag to join split pdf pages together (def: false)"
      exit 0
      ;;
    --)
      shift
      break
      ;;
    *)
      show_error "Error"
      exit 3
      ;;
  esac
done

# Checks
if ! [[ -v IN ]]; then
  show_error "No input file specified. Exiting."
  exit 3
fi

if ! [[ -v FIRST ]]; then
  FIRST=1
fi

if ! [[ -v LAST ]]; then
  LAST=$PAGES
fi

if (( LAST > PAGES )); then
  LAST=$PAGES
fi

if (( FIRST > PAGES )); then
  show_error "Starting page doesn't exist. The file only has $PAGES pages."
  exit 3
fi

if (( FIRST > LAST )); then
  show_error "What are you playing at?"
  exit 3
fi

# Split the pdf out into the individual files. The if statements are needed so
# that the filenames will get sorted in numerical order. Otherwise, the glob
# used to join the pages at the end won't work. For examples, 02 is sorted
# before 10, but 2 is placed after.
if (( FIRST >= 10 )); then
  pdfseparate -f $FIRST -l "$LAST" "$IN" "$OUT-%d.pdf"
elif (( LAST >= 10 )); then
  if (( LAST < 10 )); then
    pdfseparate -f $FIRST -l "$LAST" "$IN" "$OUT-0%d.pdf"
  fi
  if (( LAST >= 10 )); then
    pdfseparate -f $FIRST -l 9 "$IN" "$OUT-0%d.pdf"
    pdfseparate -f 10 -l "$LAST" "$IN" "$OUT-%d.pdf"
  fi
else
  pdfseparate -f $FIRST "$IN" "$OUT-0%d.pdf"
fi

# Join
if [[ -v JOINPDFS ]]; then
  if [[ $JOINPDFS = true ]]; then
    NEW="${IN%.*}-new.pdf"
    rm -f "$NEW"
    pdfunite "${OUT}"-*.pdf "$NEW"
    rm "${OUT}"-[0-9]*.pdf
  fi
fi
