#! /bin/bash
set -eu
source globals

! check_command bc ffprobe mpv parallel && exit 3


#
# Functions
#

check_inputs() {
  local item
  for item in "${@}"; do
    if [ -L "${item}" ]; then
      item="$(readlink -f "${item}")"
    fi
    if [ -d "${item}" ] || [ -f "${item}" ]; then
      continue
    else
      return 1
    fi
  done
  return 0
}

check_duration() {
  local duration
  duration="$(ffprobe -v error -show_entries stream=duration -select_streams a:0 -of default=noprint_wrappers=1:nk=1 file:"${1}")"
  if [ "$(echo "${duration} > ${CUTOFF}" | bc -l)" -eq 1 ]; then
    return 0
  else
    return 1
  fi
}
export -f check_duration

print_list() {
  if [[ "${CUTOFF}" = 0 ]]; then
    find "${IN[@]}" -type f -name "*.${FORMAT}" -print
  else
    find "${IN[@]}" -type f -name "*.${FORMAT}" -print0 | \
      parallel -0 'check_duration {} && echo {}'
  fi
}


#
# Globals
#

CUTOFF=0
FORMAT=mp3
SHUFFLE=false
REPLAYGAIN=album


#
# Parse command line variables.
#

OPTIONS=sf:c:
LONGOPTIONS=shuffle,format:,cutoff:
PARSED=$(getopt -o ${OPTIONS} --long ${LONGOPTIONS} -n "$0" -- "$@")
eval set -- "$PARSED"

while [ $# -ge 1 ]; do
  case "$1" in
    -c|--cutoff)
      CUTOFF="${2}"
      shift 2
      ;;
    -f|--format)
      FORMAT="${2}"
      shift 2
      ;;
    -s|--shuffle)
      SHUFFLE=true
      shift
      ;;
    --)
      shift
      break
      ;;
    *)
      show_error "ERROR: Unknown argument ${1@Q}. Exiting."
      exit 3
      ;;
  esac
done


#
# Main
#

IN=("${@}")
! check_inputs "${IN[@]}" && exit 3
export CUTOFF

if "${SHUFFLE}"; then
  print_list | mpv --shuffle --no-video --replaygain="${REPLAYGAIN}" --playlist=-
else
  print_list | sort -V | mpv --no-video --replaygain="${REPLAYGAIN}" --playlist=-
fi
