#! /bin/bash
set -eu
source globals

show_listitem_v2() {
  echo -e "\033[1;37m$@\033[0m"
}
show_listitem_v3() {
  echo -e "\033[1;30m$@\033[0m"
}

show_error "1;31: error"
show_info "1;32: info"
show_warning "1;33: warning"
show_question "1;34: question"
show_success "1;35: success"
show_header "1;36: header"
show_listitem "0;37: listitem"
show_listitem_v2 "1;37: unused"
show_listitem_v3 "1;30: unused"
