#! /bin/bash
set -eu

ROOT="$(dirname "${0}")"

source "${ROOT}"/globals

! check_command date && exit 3

BASE=

if [[ -v BASE ]] && [ -n "${BASE}" ]; then
  date -d "$(date -d "$(date "+${BASE} %H:%M:%S")") ${*:++${*}}"
else
  date -d "${*:++${*}}"
fi
