#! /bin/bash
set -eu
source globals


#
# Functions
#

function migrate_symlink() {
  symlink="${1}"
  sympath="$(file ${symlink} | sed -n "s,.*symbolic link to \(.*\)$,\1,p")"
  if [[ "${sympath}" =~ ^/home/${oldname} ]]; then
    newsympath=$(echo ${sympath} | sed -e "s/${oldname}/${newname}/g")
    rm "${symlink}"
    ln -s "${newsympath}" "${symlink}"
  fi
}
export -f migrate_symlink

function check_username() {
  local re='^[a-z_][a-z0-9_-]*$'
  (( ${#1} > 16 )) && return 1
  [[ $1 =~ $re ]]
}


#
# Parse command line parameters
#

OPTIONS=o:n:
LONGOPTIONS=old:,new:
PARSED=$(getopt -o ${OPTIONS} --long ${LONGOPTIONS} -n "$0" -- "$@")
eval set -- "$PARSED"

while [ $# -ge 1 ]; do
  case "$1" in
    -o|--old)
      oldname=${2}
      if ! $(check_username "${oldname}"); then
        show_error "${oldname} is not a valid name. Exiting."
        exit
      fi
      shift 2
      ;;
    -n|--new)
      newname=${2}
      if ! $(check_username "${newname}"); then \
        show_error "${newname} is not a valid name. Exiting."
        exit
      fi
      shift 2
      ;;
    --)
      shift
      break
      ;;
    *)
      show_error "Error"
      exit 3
      ;;
  esac
done

# If the user didn't supply user names via that command line, ask for them in
# the prompt.
if ! [[ -v oldname ]]; then
  oldname=$(ask_question "Change which user name?")
  if ! $(check_username "${oldname}"); then
    show_error "${oldname} is not a valid name. Exiting."
    exit
  fi
fi
if ! [[ -v newname ]]; then
  newname=$(ask_question "What is the new user name?")
  if ! $(check_username "${newname}"); then \
    show_error "${newname} is not a valid name. Exiting."
    exit
  fi
fi

# Make sure that oldname and newname entries are valid.
if [[ -z "$oldname" ]]; then echo "Error: empty old user name."; fi
if [[ -z "$newname" ]]; then echo "Error: empty new user name."; fi

export oldname
export newname

#
# Rename user and migrate files
#

# Check that old user exists.
if ! $(getent group | grep ^${oldname} >/dev/null); then
  show_error "User ${oldname} does not exist. Exiting."
  exit
fi

# Check that old user has no currently running processes.
if ps -u "${oldname}" >/dev/null 2>&1; then
  show_error "User ${oldname} has running processes. Exiting."
  exit
fi

# Check that newname is not an existing group.
if $(getent group | grep ${newname} >/dev/null); then
  show_error "${newname} already taken (see getent group output). Exiting."
  exit
fi

# Migrate the user.
show_info "Renaming '${oldname}' to '${newname}' (provide sudo password)."
sudo usermod -l ${newname} -d /home/${newname} -m ${oldname}
sudo groupmod -n ${newname} ${oldname}

show_info "Fixing symlinks in /home/${newname} (provide ${newname} pasword)."
su ${newname} -c "find /home/${newname} -type l -exec bash -c 'migrate_symlink "{}"' \;"

# Prompt to change password.
check=$(ask_question "Change password for ${newname}? (y/N)")
if [[ $check =~ ^([Yy][Ee][Ss]|[Yy])$ ]]; then
  passwd ${newname}
fi

show_success "Migrated!"
