#!/bin/bash

# SPDX-FileCopyrightText: 2019 - 2024 sudorook <daemon@nullcodon.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.

set -eu

ROOT="$(dirname "${0}")"

source "${ROOT}"/globals

if ! [[ -v 1 ]] || ! [ -f "${1}" ]; then
  show_error "ERROR: ${1@Q} does not exist. Exiting."
  exit 1
fi

EXTENSION="${1##*.}"

case "${EXTENSION,,}" in
  rmd | rmarkdown)
    if check_command R; then
      R -q -e "if (require(rmarkdown)) { options(encoding='UTF-8'); render('${1}') }"
    fi
    ;;
  tex | latex)
    if check_command lualatex; then
      lualatex -shell-escape "${1}"
    fi
    ;;
  jmd | jmarkdown)
    if check_command julia; then
      julia -e "using Weave; weave(\"${1}\")"
    fi
    ;;
  *)
    show_error "${EXTENSION@Q} not supported. Exiting."
    exit 3
    ;;
esac
