#! /bin/bash
set -eu

ROOT="$(dirname "${0}")"

source "${ROOT}"/globals

if ! [[ -v 1 ]] || ! [ -f "${1}" ]; then
  show_error "ERROR: ${1@Q} does not exist. Exiting."
  exit 1
fi

EXTENSION="${1##*.}"

case "${EXTENSION,,}" in
  rmd | rmarkdown)
    if check_command R; then
      R -q -e "if (require(rmarkdown)) { options(encoding='UTF-8'); render('${1}') }"
    fi
    ;;
  tex | latex)
    if check_command lualatex; then
      lualatex -shell-escape "${1}"
    fi
    ;;
  jmd | jmarkdown)
    if check_command julia; then
      julia -e "using Weave; weave(\"${1}\")"
    fi
    ;;
  *)
    show_error "${EXTENSION@Q} not supported. Exiting."
    exit 3
    ;;
esac
