#! /bin/bash
set -eu

ROOT="$(dirname "${0}")"

source "${ROOT}"/globals

#
# Functions
#

function check_file {
  if ! [[ -L "${1}" ]]; then
    show_warning "WARNING: ${1@Q} not a symbolic link."
    return 1
  fi

  if ! [[ -e "${1}" ]]; then
    show_warning "WARNING: ${1@Q} broken symbolic link."
    return 1
  fi

  if ! [[ -f "$(readlink -f "${1}")" ]]; then
    show_warning "WARNING: ${1@Q} link needs to point to a file."
    return 1
  fi

  for dir in "${PROTECT_DIRS[@]}"; do
    if [[ "$(readlink -f "${1}")" == "$(readlink -f "${dir}")"* ]]; then
      show_warning "WARNING: files in ${dir@Q} are protected. Skipping."
      return 1
    fi
  done

  return 0
}

function rmlink {
  rm "${VERBOSE:+-v}" "$(readlink -f "${1}")"
  rm "${VERBOSE:+-v}" "${1}"
}

#
# Globals
#

VERBOSE=true
PROTECT_DIRS=()

#
# Main
#

for FILE in "${@}"; do
  if check_file "${FILE}"; then
    rmlink "${FILE}"
  fi
done
