#! /bin/bash
set -eu
source globals

! check_command xrandr dconf && exit 3


function print_usage {
  show_header "Usage:"
  echo "  -i|--input         display ID"
  echo "  -r|--rotation      rotation (left, right, normal, or inverted)"
}

function display_connected {
  if xrandr | grep "^${ID} connected" >/dev/null; then
    return 0
  else
    return 1
  fi
}

ID="HDMI-1"
ROTATION=left
VERTICAL_BG="/usr/share/backgrounds/timed/24-hours-timed.xml"
HORIZONTAL_BG="/usr/share/backgrounds/timed/island-timed.xml"

OPTIONS=i:r:h
LONGOPTIONS=input:,rotation:,help
PARSED=$(getopt -o ${OPTIONS} --long ${LONGOPTIONS} -n "$0" -- "$@")
eval set -- "$PARSED"

while [ $# -ge 1 ]; do
  case "$1" in
    -i|--input)
      ID="$2"
      shift 2
      ;;
    -r|--rotation)
      ROTATION="$2"
      shift 2
      ;;
    -h|--help)
      print_usage
      shift
      break
      ;;
    --)
      shift
      break
      ;;
    *)
      show_error "ERROR: invalid flag ${1}."
      print_usage
      exit 3
      ;;
  esac
done

if ! display_connected; then
  show_error "ERROR: display ${ID} not found. Exiting."
  exit 3
fi

case ${ROTATION} in
  right)
    xrandr --output "${ID}" --rotate right
    dconf write /org/cinnamon/desktop/background/picture-uri "'file://${VERTICAL_BG}'"
    ;;
  left)
    xrandr --output "${ID}" --rotate left
    dconf write /org/cinnamon/desktop/background/picture-uri "'file://${VERTICAL_BG}'"
    ;;
  normal)
    xrandr --output "${ID}" --rotate normal
    dconf write /org/cinnamon/desktop/background/picture-uri "'file://${HORIZONTAL_BG}'"
    ;;
  inverted)
    xrandr --output "${ID}" --rotate inverted
    dconf write /org/cinnamon/desktop/background/picture-uri "'file://${HORIZONTAL_BG}'"
    ;;
  *)
    show_error "ERROR: invalid rotation ${ROTATION@Q}. Exiting."
    print_usage
    exit 3
    ;;
esac
