#!/bin/bash

# SPDX-FileCopyrightText: 2021 - 2024 sudorook <daemon@nullcodon.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.

set -Eeu

ROOT="$(dirname "${0}")"

source "${ROOT}"/globals

#
# Check inputs and requirements.
#

! check_command scour && exit 3

if ! [ -f "${1}" ]; then
  show_error "ERROR: ${1} not found. Exiting."
  exit 3
fi

if ! [[ "$(file --mime-type -b "${1}")" =~ (svg|svg\+xml)$ ]]; then
  show_error "ERROR: ${1} not an SVG. Exiting."
  exit 3
fi

#
# Main
#

TMP="$(mktemp)"

trap 'rm -f "${TMP}"; exit' INT TERM ERR
scour -i "${1}" -o "${TMP}"
mv "${TMP}" "${1}"
sync
