#! /bin/bash
set -Eeu
source globals

#
# Check inputs and requirements.
#

! check_command scour && exit 3

if ! [ -f "${1}" ]; then
  show_error "ERROR: ${1} not found. Exiting."
  exit 3
fi

if ! [[ "$(file --mime-type -b "${1}")" =~ (svg|svg\+xml)$ ]]; then
  show_error "ERROR: ${1} not an SVG. Exiting."
  exit 3
fi

#
# Main
#

TMP="$(mktemp)"

trap 'rm -f "${TMP}"; exit' INT TERM ERR
scour -i "${1}" -o "${TMP}"
mv "${TMP}" "${1}"
sync
