#! /bin/bash
set -eu
source globals


#
# Global functions
#

function sloppy_seek {
  find ${HOME}/ \
    ! -path "${HOME}/Desktop*" \
    ! -path "${HOME}/Documents*" \
    ! -path "${HOME}/Downloads*" \
    ! -path "${HOME}/Music*" \
    ! -path "${HOME}/Pictures*" \
    ! -path "${projectdir}*" \
    ! -path "${HOME}/Public*" \
    ! -path "${HOME}/Sync*" \
    ! -path "${HOME}/Templates*" \
    ! -path "${HOME}/Videos*" \
    ! -path "${pkgbuilddir}*" \
    -iname "*${1}*" -o -iname ".*${1}*" 2>/dev/null || true
}

function precise_seek {
  find ${HOME}/ \
    ! -path "${HOME}/Desktop*" \
    ! -path "${HOME}/Documents*" \
    ! -path "${HOME}/Downloads*" \
    ! -path "${HOME}/Music*" \
    ! -path "${HOME}/Pictures*" \
    ! -path "${projectdir}*" \
    ! -path "${HOME}/Public*" \
    ! -path "${HOME}/Sync*" \
    ! -path "${HOME}/Templates*" \
    ! -path "${HOME}/Videos*" \
    ! -path "${pkgbuilddir}*" \
    -name "${1}" -o -name ".${1}" \
    -o -name ".${1,,}" -o -name ".${1,,}" \
    -o -name ".${1^,}" -o -name ".${1^}" 2>/dev/null || true
}

function destroy {
  xargs -n 1 -exec rm -rf
  show_success "Target(s) eliminated."
}


#
# Parse command line options
#

OPTIONS=ps
LONGOPTIONS=precise,sloppy
PARSED=$(getopt -o ${OPTIONS} --long ${LONGOPTIONS} -n ${0} -- ${@})
eval set -- ${PARSED}
MODE=

while [ ${#} -ge 1 ]; do
  case ${1} in
    -p|--precise)
      MODE=precise
      shift
      ;;
    -s|--sloppy)
      MODE=sloppy
      shift
      ;;
    --)
      shift
      break
      ;;
    *)
      show_error "Error: invalid flag."
      exit 3
      ;;
  esac
done


#
# Run seeker and destroyer
#

if [ ${#} != 1 ]; then
  show_error "Error: incorrect # of arguments."
  show_error "Pass the name of a file or directory to seek and destroy."
fi

case ${MODE} in
  precise)
    show_header "--- Running precise seeker ---"
    if test "$(precise_seek ${1})"; then
      precise_seek ${1}
      check=$(ask_question 'Permission to destroy? (y/N)')
      if [[ ${check} =~ ^([yY][eE][sS]|[yY])$ ]]; then
        echo "Yessir!"
        precise_seek ${1} | destroy
      else
        echo "As you wish..."
      fi
    else
      echo "Target(s) not found. Standing down."
    fi
    ;;
  sloppy)
    show_header "--- Running sloppy seeker ---"
    if test "$(sloppy_seek ${1})"; then
      sloppy_seek ${1}
      check=$(ask_question 'Permission to destroy? (y/N)')
      if [[ ${check} =~ ^([yY][eE][sS]|[yY])$ ]]; then
        echo "Yessir!"
        sloppy_seek ${1} | destroy
      else
        echo "As you wish..."
      fi
    else
      echo "Target(s) not found. Standing down."
    fi
    ;;
  *)
    show_error "Error: seeker mode ${MODE} is incorrect."
    exit
    ;;
esac
