#! /bin/bash
set -euo pipefail
source globals

# Check that GDM is installed.
command -v pacman >/dev/null 2>&1 && {
  if ! pacman -Qi gdm >/dev/null 2>&1; then
    show_error "GDM is not installed. Exiting."
    exit 3
  fi
}

command -v apt >/dev/null 2>&1 && {
  if dpkg -s gdm3 >/dev/null 2>&1; then
    show_error "GDM is not installed. Exiting."
    exit 3
  fi
}

# Get the current GTK theme.
case $XDG_CURRENT_DESKTOP in
  X-Cinnamon)
    GTKTHEME=$(gsettings get org.cinnamon.desktop.interface gtk-theme | sed -e "s/'//g")
    ;;
  GNOME|ubuntu:GNOME)
    GTKTHEME=$(gsettings get org.gnome.desktop.interface gtk-theme | sed -e "s/'//g")
    ;;
  *)
    show_error "$XDG_CURRENT_DESKTOP environment not supported."
    exit 3
    ;;
esac

GNOMESHELLDIR="/usr/share/gnome-shell"
GNOMESHELLBAK="/usr/share/gnome-shell-$(date +%Y%m%d-%I%M%S)"

if [[ -d "/usr/share/themes/${GTKTHEME}" ]]; then
  show_header "Setting GDM login theme to ${GTKTHEME}."

  show_info "Backing up current GDM settings to ${GNOMESHELLBAK}."
  sudo cp -r "${GNOMESHELLDIR}" "${GNOMESHELLBAK}"

  if [[ "${GTKTHEME}" =~ Adapta ]] || [[ "${GTKTHEME}" =~ Plata ]]; then
    show_info "Copying over ${GTKTHEME} GDM theme."
    sudo cp -rf /usr/share/themes/"${GTKTHEME}"/gnome-shell/* "${GNOMESHELLDIR}"
    sudo cp -f \
      /usr/share/themes/"${GTKTHEME}"/gnome-shell/extensions/window-list/classic.css \
      "${GNOMESHELLDIR}"/extensions/window-list@gnome-shell-extensions.gcampax.github.com/
    sudo cp -f \
      /usr/share/themes/"${GTKTHEME}"/gnome-shell/extensions/window-list/stylesheet.css \
      "${GNOMESHELLDIR}"/extensions/window-list@gnome-shell-extensions.gcampax.github.com/
  elif [[ "${GTKTHEME}" =~ Materia ]]; then
    show_info "Building ${GTKTHEME} GDM theme from GResource file."
    sudo glib-compile-resources \
      --target="/usr/share/gnome-shell/gnome-shell-theme.gresource" \
      --sourcedir="/usr/share/themes/${GTKTHEME}/gnome-shell" \
      "/usr/share/themes/${GTKTHEME}/gnome-shell/gnome-shell-theme.gresource.xml"
  fi
fi

show_success "Done."
