#! /bin/bash
set -eu
source globals

# Check that GDM is installed.
command -v pacman >/dev/null 2>&1 && {
  if ! pacman -Qi gdm >/dev/null 2>&1; then
    show_error "GDM is not installed. Exiting."
    exit 3
  fi
}

command -v apt >/dev/null 2>&1 && {
  if dpkg -s gdm >/dev/null 2>&1; then
    show_error "GDM is not installed. Exiting."
    exit 3
  fi
}

# Get the current GTK theme.
case $XDG_CURRENT_DESKTOP in
  X-Cinnamon)
    GTKTHEME=$(gsettings get org.cinnamon.desktop.interface gtk-theme | sed -e "s/'//g")
    ;;
  GNOME|ubuntu:GNOME)
    GTKTHEME=$(gsettings get org.gnome.desktop.interface gtk-theme | sed -e "s/'//g")
    ;;
  *)
    show_error "$XDG_CURRENT_DESKTOP environment not supported."
    exit 3
    ;;
esac

GNOMESHELLDIR="/usr/share/gnome-shell"
GNOMESHELLBAK="/usr/share/gnome-shell-$(date +%Y%m%d-%I%M%S)"

command -v pacman >/dev/null 2>&1 && {
  if ! pacman -Qi gdm > /dev/null 2>&1; then
    show_error "GDM is not installed. Exiting."
    exit 3
  fi
}

command -v apt >/dev/null 2>&1 && {
  if ! dpkg -s gdm3 > /dev/null 2>&1; then
    show_error "GDM is not installed. Exiting."
    exit 3
  fi
}

show_info "Backing up current GDM settings to ${GNOMESHELLBAK}."
sudo cp -rf "${GNOMESHELLDIR}" "${GNOMESHELLBAK}"

show_info "Copying over ${GTKTHEME} GDM theme."
sudo cp -rf /usr/share/themes/"${GTKTHEME}"/gnome-shell/* "${GNOMESHELLDIR}"

if [[ "${GTKTHEME}" =~ Adapta ]]; then
  sudo cp -f /usr/share/themes/Adapta/gnome-shell/extensions/window-list/* \
    "${GNOMESHELLDIR}"/extensions/window-list@gnome-shell-extensions.gcampax.github.com/
  sudo rm -rf "${GNOMESHELLDIR}/extensions/window-list"
  sudo rm -rf "${GNOMESHELLDIR}/extensions/workspaces-to-dock"
fi

show_success "Done."
