#! /bin/bash
set -eu
source globals

#
# Check inputs and requirements
#

! check_command bs1770gain && exit 3

#
# Main
#

TMPDIR="$(mktemp -d)"
trap 'rm -rf "${TMPDIR}"; exit' INT TERM ERR

if [ $# = 2 ]; then
  if [[ "$*" =~ ^-k ]]; then
    bs1770gain "${2}" -o "${TMPDIR}"
    mv "${2}" "${2}.bak"
    mv "${TMPDIR}" "${2}"
  elif [[ "$*" =~ \ -k$ ]]; then
    bs1770gain "${1}" -o "${TMPDIR}"
    mv "${1}" "${1}.bak"
    mv "${TMPDIR}" "${1}"
  fi
elif [ $# = 1 ]; then
  bs1770gain "${1}" -o "${TMPDIR}"
  rm -r "${1}"
  mv "${TMPDIR}" "${1}"
fi
