#! /bin/bash
set -eu
source globals

#
# Check inputs and requirements
#

! check_command bs1770gain && exit 3

function check_inputs {
  local input

  if ! [ "${#}" -ge 0 ]; then
    show_error "ERROR: no inputs given. Exiting."
  fi

  for input in "${@}"; do
    if ! [ -e "${input}" ]; then
      show_error "ERROR: ${input@Q} not found. Exiting."
      exit 3
    fi
  done
}

function print_usage {
  show_header "Usage: set-replaygain <file(s) or director(ies)>"
  show_listitem \
    "  -k|--keep   flag to keep original files/directories (default: false)"
  show_listitem \
    "  -h|--help   print (this) help message"
}


#
# Main
#

KEEP=false

OPTIONS=kh
LONGOPTIONS=keep,help
PARSED=$(getopt -o ${OPTIONS} --long ${LONGOPTIONS} -n "${0}" -- "${@}")
eval set -- "${PARSED}"

while [ "${#}" -ge 1 ]; do
  case "${1}" in
    -k|--keep)
      KEEP=true
      shift 1
      ;;
    -h|--help)
      print_usage
      exit
      ;;
    --)
      shift
      break
      ;;
    *)
      show_error "ERROR: invalid flag."
      exit 3
      ;;
  esac
done

TMPDIR="$(mktemp -d)"
trap 'rm -rf "${TMPDIR}"; exit' INT TERM ERR

# Check that input files/directories exist before computing replay gain.
check_inputs  "${@}"

# Generate name for backup directory.
if [[ "${KEEP}" = true ]]; then
  if [ "${#}" -eq 1 ]; then
    if [ -d "${1}" ]; then
      BACKUPDIR="${1}_$(date +%Y%m%d-%H%M%S)"
    else
      show_warning "Why compute album replay gain for one file? Stopping..."
      exit
    fi
  else
    BACKUPDIR="backup_$(date +%Y%m%d-%H%M%S)"
  fi
fi

# Move files into place.
if [ "${#}" -eq 1 ]; then
  bs1770gain "${@}" -o "${TMPDIR}"
  if [[ "${KEEP}" = true ]]; then
    mkdir -p "${BACKUPDIR}"
    mv "${1}" "${BACKUPDIR}"
    mv "${TMPDIR}" "${1}"
  else
    mv "${1}" "${1}.bak"
    mv "${TMPDIR}" "${1}"
    rm -r "${1}.bak"
  fi
else
  for ITEM in "${@}"; do
    mkdir -p "${TMPDIR}/$(basename "${ITEM}")"
    bs1770gain "${ITEM}" -o "${TMPDIR}/$(basename "${ITEM}")"
    if [[ "${KEEP}" = true ]]; then
      mkdir -p "${BACKUPDIR}/$(basename "${ITEM}")"
      mv "${ITEM}" "${BACKUPDIR}/$(basename "${ITEM}")"
      mv "${TMPDIR}/$(basename "${ITEM}")" "${ITEM}"
    else
      mv "${ITEM}" "${ITEM}.bak"
      mv "${TMPDIR}/$(basename "${ITEM}")" "${ITEM}"
      rm -r "${ITEM}.bak"
    fi
  done
  rmdir "${TMPDIR}"
fi

sync
