#! /bin/bash
set -eu
source globals

function cleanup() {
  if [ -f ${1}.bak ]; then
    mv -f ${1}.bak ${1}
  fi
}

trap cleanup INT TERM EXIT

if ! [ -f "${1}" ]; then
  show_error "File doesn't exist."
  exit 1
fi

if [ "${1##*.}" = "qcow2" ]; then
  OLD_SIZE=$(du -h "${1}" | cut -f1)
  sudo bash -c "{
    mv -f "${1}" "${1}".bak
    qemu-img convert -O qcow2 "${1}".bak  "${1}"
    chmod --reference="${1}".bak "${1}"
    rm -f "${1}".bak
  }"
  NEW_SIZE=$(du -h "${1}" | cut -f1)
  show_success "Compressed from ${OLD_SIZE} to ${NEW_SIZE}."
  sync
else
  show_error "${1} is not a qcow2 file."
  exit 1
fi
