#! /bin/bash
set -euo pipefail
source globals

! check_command qemu-img && exit 3

#
# Functions
#

function abort() {
  if [ -f "${1}.bak" ]; then
    mv -f "${1}.bak" "${1}"
  fi
}

function do_shrink() {
  if test -r "${1}"; then
    if ! [[ "$(file -b "${1}")" =~ QCOW ]]; then
      echo -e $'\033[1;31m'"ERROR: ${1@Q} is not a QCOW2 file. Exiting."$'\033[0m' 1>&2
      exit 3
    fi
  else
    echo -e $'\033[1;31m'"ERROR: Cannot read ${1@Q}. Exiting."$'\033[0m' 1>&2
  fi

  echo -e $'\033[1;32m'"Shrinking..."$'\033[0m'
  mv -f "${1}" "${1}.bak"
  qemu-img convert -O qcow2 "${1}.bak" "${1}"
  chmod --reference="${1}.bak" "${1}"
  chown --reference="${1}.bak" "${1}"
  rm -f "${1}.bak"
}
FUNCTION=$(declare -f do_shrink)


#
# Globals
#

QCOW2="${1}"

# Check inputs and requirements.
if ! [ -f "${QCOW2}" ]; then
  show_error "ERROR: ${QCOW2@Q} doesn't exist. Exiting."
  exit 3
fi

OWNER="$(stat "${QCOW2}" -c "%U")"


#
# Main
#

trap 'abort ${QCOW2}' INT TERM ERR

OLD_SIZE=$(du -h "${QCOW2}" | cut -f1)

case "${OWNER}" in
  "${USER}")
    do_shrink "${QCOW2}"
    ;;
  root)
    show_info "${QCOW2@Q} owned by ${OWNER@Q}. Trying sudo..."
    sudo bash -c "${FUNCTION} && do_shrink ${QCOW2}"
    ;;
  nobody|kvm|libvirt-qemu)
    show_error "ERROR: Cannot edit running instance. Exiting."
    exit 3
    ;;
  *)
    if [[ "$(users)" =~ (^|[[:space:]])${OWNER}($|[[:space:]]) ]]; then
      show_warning "${QCOW2@Q} owned by ${OWNER}. Trying su..."
      su "${OWNER}" - bash -c "${FUNCTION} && do_shrink ${QCOW2}"
    else
      show_error "User ${OWNER@Q} not recognized. Exiting."
      exit 3
    fi
    ;;
esac

NEW_SIZE=$(du -h "${QCOW2}" | cut -f1)

show_success "Compressed ${QCOW2@Q} from ${OLD_SIZE} to ${NEW_SIZE}."
sync
