#! /bin/bash
set -eu
source globals

! check_command ffmpeg mid3v2 && exit 3

#
# Functions
#

function strip_wrapper {
  local in="${1}"
  local extension=${1##*.}
  ffmpeg -i file:"${in}" -map_metadata -1 -map 0:a -c:a copy -f "${extension}" file:"${TMP}" -y
  mid3v2 -D "${TMP}"
  cp "${TMP}" "${in}"
  sync
}

#
# Check inputs and requirements.
#

if ! [ -f "${1}" ]; then
  show_error "ERROR: ${1@Q} not a file. Exiting."
  exit 3
fi

#
# Main
#

TMP="$(mktemp)"
trap 'rm -f ${TMP}; exit' INT TERM ERR EXIT

for ITEM in "${@}"; do
  if [ -f "${ITEM}" ]; then
    strip_wrapper "${ITEM}"
  else
    show_warning "WARNING: skipping ${ITEM@Q}."
  fi
done
