#! /bin/bash
set -Eeuo pipefail
source globals

! check_command ffmpeg mid3v2 && exit 3

#
# Functions
#

function do_strip_mp3 {
  local in="${1}"
  local tmp
 
  tmp=$(mktemp)
  trap 'rm -vf "${tmp}"' INT RETURN ERR TERM

  ffmpeg -v warning -i file:"${in}" \
    -map_metadata -1 -map 0:a -c:a copy -f mp3 file:"${tmp}" -y
  mid3v2 -D "${tmp}"

  mv "${tmp}" "${in}"
  sync
}
export -f do_strip_mp3


#
# Main
#

if [ $# -eq 1 ] && [ -f "${1}" ]; then
  echo "Stripping ${1@Q}"
  do_strip_mp3 "${1}"
else
  show_header "Stripping files in ${*@Q}..."
  if command -v parallel >/dev/null; then
    find "$@" -type f -iname "*.mp3" -print0 | \
      parallel -0 'echo {} && do_strip_mp3 {}'
  else
    find "$@" -type f -iname "*.mp3" -exec \
      sh -c 'echo "${1}" && do_strip_mp3 "${1}"' sh {} \;
  fi
fi
