#! /bin/bash
set -Eeuo pipefail

ROOT="$(dirname "${0}")"

source "${ROOT}"/globals

! check_command ffmpeg find xargs && exit 3

#
# Functions
#

function do_strip_flac {
  local in="${1}"
  local tmp

  tmp=$(mktemp)
  trap 'rm -vf "${tmp}"' INT RETURN ERR TERM

  ffmpeg -v warning -i file:"${in}" -c copy -f ogg - |
    ffmpeg -v warning -i - \
      -map_metadata -1 -map 0:a -c:a copy -vn \
      -fflags +bitexact -flags:a +bitexact \
      -f flac file:"${tmp}" -y

  mv "${tmp}" "${in}"
}
export -f do_strip_flac

function do_strip_mp3 {
  local in="${1}"
  local tmp

  tmp=$(mktemp)
  trap 'rm -vf "${tmp}"' INT RETURN ERR TERM

  ffmpeg -v warning -i file:"${in}" -c copy -f avi - |
    ffmpeg -v warning -i - \
      -map_metadata -1 -map 0:a -c:a copy \
      -fflags +bitexact -flags:v +bitexact -flags:a +bitexact \
      -f mp3 file:"${tmp}" -y

  mv "${tmp}" "${in}"
}
export -f do_strip_mp3

function strip_wrapper {
  local ext="${1##*.}"
  case "${ext,,}" in
    flac)
      do_strip_flac "${1}"
      ;;
    mp3)
      do_strip_mp3 "${1}"
      ;;
  esac
}
export -f strip_wrapper

#
# Main
#

show_header "Stripping ${*@Q}..."

if [ $# -eq 0 ]; then
  show_error "ERROR: No path(s) provided. Exiting."
  exit 3
fi

find "${@}" -type f \( -iname "*.flac" -o -iname "*.mp3" \) -print0 |
  xargs -0 -I{} -P "$(nproc)" bash -c 'strip_wrapper "{}"'

sync
