#!/bin/bash

# SPDX-FileCopyrightText: 2022 - 2024 sudorook <daemon@nullcodon.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.

set -eu

ROOT="$(dirname "${0}")"

source "${ROOT}"/globals

if ! [ -L "${1}" ]; then
  show_error "ERROR: ${1@Q} not a symlink. Exiting."
  exit 3
fi

if readlink -e "${1}" > /dev/null; then
  SYM="${1}"
  REF="$(readlink "${SYM}")"
  ABSSYM="$(realpath -s "${SYM}")"
  ABSREF="$(readlink -f "${SYM}")"

  if [[ "${REF::1}" = "/" ]]; then
    rm -v "${SYM}"
    mv -v "${REF}" "${SYM}"
    ln -s "${ABSSYM}" "${REF}"
  else
    rm -v "${SYM}"
    mv -v "${ABSREF}" "${SYM}"
    ln -sr "${SYM}" "${ABSREF}"
  fi

  sync

  show_success "Swapped ${SYM@Q} and ${REF@Q}"
fi
