#! /bin/bash
set -eu
source globals

get_terminal_profiles() {
  IFS=' ' read -r -a ids <<< \
    "$(dconf read /org/gnome/terminal/legacy/profiles:/list | tr -d "[]',")"
  names=()
  declare -A profiles
  for id in "${ids[@]}"; do
    names+=("$(dconf read /org/gnome/terminal/legacy/profiles:/:$id/visible-name)")
  done
}

switch_terminal_profile() {
  local idx=0
  for name in ${names[@]}; do
    if [ "$name" = "'$1'" ]; then
      dconf write /org/gnome/terminal/legacy/profiles:/default "'${ids[$idx]}'"
    fi
    idx=$((idx+1))
  done
}

switch_vim_background() {
  if [ -f ${HOME}/.vimrc ]; then
    if [ "$1" = "Dark" ]; then
      sed -i "s/^set background=.*$/set background=dark/g" ${HOME}/.vimrc
      sed -i "s/^set bg=.*$/set bg=dark/g" ${HOME}/.vimrc
    elif [ "$1" = "Light" ]; then
      sed -i "s/^set background=.*$/set background=light/g" ${HOME}/.vimrc
      sed -i "s/^set bg=.*$/set bg=light/g" ${HOME}/.vimrc
    fi
  fi
}

set_gtk_theme() {
  case $XDG_CURRENT_DESKTOP in
    X-Cinnamon)
      gsettings set org.cinnamon.desktop.interface gtk-theme "'$1'"
      gsettings set org.cinnamon.desktop.wm.preferences theme "'$1'"
      if [[ "$1" =~ "-Eta" ]]; then
        gsettings set org.cinnamon.theme name "'${1%-*}'"
      elif [[ "$1" =~ "-Darker" ]]; then
        gsettings set org.cinnamon.theme name "'${1%er}'"
      else
        gsettings set org.cinnamon.theme name "'$1'"
      fi
      ;;
    GNOME)
      gsettings set org.gnome.desktop.wm.preferences theme "'$1'"
      gsettings set org.gnome.desktop.interface gtk-theme "'$1'"
      gnome-shell-extension-tool -e "user-theme@gnome-shell-extensions.gcampax.github.com" || true >/dev/null
      gsettings set org.gnome.shell.extensions.user-theme name "'$1'"
      ;;
    *)
      show_error "$XDG_CURRENT_DESKTOP environment not supported."
      exit 3
      ;;
  esac

  gtksettings="${HOME}/.config/gtk-3.0/settings.ini"
  if [[ "$1" =~ "Nokto" ]] || [[ "$1" =~ "Dark" ]]; then
    sed -i "s/^gtk-application-prefer-dark-theme=false$/gtk-application-prefer-dark-theme=true/g" ${gtksettings}
    sed -i "s/^gtk-application-prefer-dark-theme=0$/gtk-application-prefer-dark-theme=1/g" ${gtksettings}
    switch_terminal_profile "Dark"
    switch_vim_background "Dark"
  else
    sed -i "s/^gtk-application-prefer-dark-theme=true$/gtk-application-prefer-dark-theme=false/g" ${gtksettings}
    sed -i "s/^gtk-application-prefer-dark-theme=1$/gtk-application-prefer-dark-theme=0/g" ${gtksettings}
    switch_terminal_profile "Light"
    switch_vim_background "Light"
  fi
}

set_icon_theme() {
  case $XDG_CURRENT_DESKTOP in
    X-Cinnamon)
      gsettings set org.cinnamon.desktop.interface icon-theme "'$1'"
      ;;
    GNOME)
      gsettings set org.gnome.desktop.interface icon-theme "'$1'"
      ;;
    *)
      show_error "$XDG_CURRENT_DESKTOP environment not supported."
      exit 3
      ;;
  esac
}

OPTIONS=g:i:
LONGOPTIONS=gtk:,icon:
PARSED=$(getopt -o ${OPTIONS} --long ${LONGOPTIONS} -n "$0" -- "$@")
eval set -- "$PARSED"

get_terminal_profiles
while [ $# -ge 1 ]; do
  case "$1" in
    -g|--gtk)
      set_gtk_theme "$2" 
      shift 2
      ;;
    -i|--icon)
      set_icon_theme "$2"
      shift 2
      ;;
    --)
      shift
      break
      ;;
    *)
      show_error "Error"
      exit 3
      ;;
  esac
done
