#! /bin/bash
set -eu
source globals

set_gtk_theme() {
  case $DESKTOP_SESSION in
    cinnamon)
      gsettings set org.cinnamon.desktop.interface gtk-theme "'$1'"
      gsettings set org.cinnamon.desktop.wm.preferences theme "'$1'"
      if [[ "$1" =~ "-Eta" ]]; then
        gsettings set org.cinnamon.theme name "'${1%-*}'"
      else
        gsettings set org.cinnamon.theme name "'$1'"
      fi
      ;;
    gnome)
      gsettings set org.gnome.desktop.wm.preferences theme "'$1'"
      gsettings set org.gnome.desktop.interface gtk-theme "'$1'"
      gnome-shell-extension-tool -e "user-theme@gnome-shell-extensions.gcampax.github.com" || true
      gsettings set org.gnome.shell.extensions.user-theme name "'$1'"
      ;;
    *)
      show_error "$DESKTOP_SESSION environment not supported."
      exit 3
      ;;
  esac
}

set_icon_theme() {
  case $DESKTOP_SESSION in
    cinnamon)
      gsettings set org.cinnamon.desktop.interface icon-theme "'$1'"
      ;;
    gnome)
      gsettings set org.gnome.desktop.interface icon-theme "'$1'"
      ;;
    *)
      show_error "$DESKTOP_SESSION environment not supported."
      exit 3
      ;;
  esac
}

OPTIONS=g:i:
LONGOPTIONS=gtk:,icon:
PARSED=$(getopt -o ${OPTIONS} --long ${LONGOPTIONS} -n "$0" -- "$@")
eval set -- "$PARSED"

while [ $# -ge 1 ]; do
  case "$1" in
    -g|--gtk)
      set_gtk_theme "$2" 
      shift 2
      ;;
    -i|--icon)
      set_icon_theme "$2"
      shift 2
      ;;
    --)
      shift
      break
      ;;
    *)
      show_error "Error"
      exit 3
      ;;
  esac
done
