#! /bin/bash
set -eu
source globals

# pacman
command -v pacman >/dev/null 2>&1 && {
  show_header "Updating Arch Linux."
  sudo pacman -Syu --noconfirm && sudo paccache -r && sudo paccache -ruk0
  echo && sleep 1
}

# apt
command -v apt >/dev/null 2>&1 && {
  show_header "Updating Debian."
  sudo apt update && sudo apt -y full-upgrade && sudo apt -y autoremove
  echo && sleep 1
}

# using go get from a bash script will result in:
#   fatal: could not read Username for 'https://github.com': terminal prompts
#   disabled
#
# setting a global alias for https://github.com/ -> git@github.com will
# probably let you circumvent the issue
#
# # primitive
# echo "Upgrading go repos."
# go get -u github.com/fogleman/primitive
# echo && sleep 1

# themes, icons
show_header "Updating GTK and icon themes."
update-themes
echo && sleep 1

# julia
command -v julia >/dev/null 2>&1 && {
  show_header "Upgrading Julia packages."
  julia -e 'Pkg.update(); using Gadfly'
  echo && sleep 1
}

# zsh
show_header "Updating zsh repos."
if command -v antigen-update >/dev/null 2>&1; then
  antigen-update
else
  for dir in ${zshdir}/*; do
    [ -d ${dir} ] && git -C ${dir} pull
  done
fi
echo && sleep 1
