#! /bin/bash
set -eu
source globals

# pacman
show_info "Updating Arch Linux."
sudo pacman -Syu --noconfirm && sudo paccache -r && sudo paccache -ruk0
echo && sleep 1

# using go get from a bash script will result in:
#   fatal: could not read Username for 'https://github.com': terminal prompts
#   disabled
#
# setting a global alias for https://github.com/ -> git@github.com will
# probably let you circumvent the issue
#
# # hugo, primitive
# echo "Upgrading go repos."
# go get -u github.com/fogleman/primitive
# echo && sleep 1

# themes, icons
show_info "Updating GTK and icon themes."
update-themes
echo && sleep 1

# julia
show_info "Upgrading Julia packages."
julia -e 'Pkg.update(); using Gadfly'
echo && sleep 1

# zsh
show_info "Updating zsh repos."
for dir in ${HOME}/.zsh/*; do
  [ -d ${dir} ] && git -C ${dir} pull
  echo && sleep 1
done
