#! /bin/bash
set -eu
source globals

function cleanup_filename() {
  vid="$1"
  name="${vid%.*}"
  extension="${vid##*.}"

  newname=$(echo "$name" | \
    sed -e "s/_\|\./\ /g" | \
    sed -e "s/\[[^][]*\]\ //g" | \
    sed -e "s/([^][]*)\ //g" | \
    sed -e "s/\ \+([^][]*)//g" | \
    sed -e "s/\ \+\[[^][]*\]//g" | \
    sed -e "s/\[[^][]*\]//g" | \
    sed -e "s/\ \(720\|1080\|480\)p.*//g" | \
    sed -e "s/\ \(19\|20\)\([0-9]\{2\}\)$//g" | \
    sed -e "s/([^][]*)//g" | \
    sed -e "s/\b\(s[0-9][0-9]e[0-9][0-9]\)/\U\1/g" | \
    sed -e "s/ *$//g")
  echo "$newname.$extension"
  return 0
}

for vid in *; do
  if [ -f "$vid" ]; then
    newvid=$(cleanup_filename "$vid")
    echo "$newvid"
  fi
done

check=$(ask_question "Is this good? (y/N)")

if [ "$check" = "y" ] || [ "$check" = "Y" ]; then
  for vid in *; do
    if [ -f "$vid" ]; then
      newvid=$(cleanup_filename "$vid")
      if [ "$vid" != "$newvid" ]; then
        mv "$vid" "$newvid"
        echo "$vid"
        echo " --> $newvid"
      else
        echo "$vid unchanged"
      fi
    fi
  done
else
  echo "Fine. Be that way."
  exit 1
fi
