#! /bin/bash
set -eu
source globals

FILE=${entrydir}/$(date -d '-6 hours' +%F).md

if ! [ -f "${FILE}" ]; then
  if ! [[ -v template ]] || [[ -z "${template}" ]]; then
    echo "# $(date -d '-6 hours' '+%A, %B %d, %Y')" >> "${FILE}"
    echo >> "${FILE}"
  elif ! [ -f "${template}" ]; then
    show_error "Template ${template} does not exist."
    exit 3
  else
    cat "${template}" >> "${FILE}"
    sed -i "s/@date@/$(date -d '-6 hours' '+%A, %B %d, %Y')/g" "${FILE}"
  fi
fi

eval "${EDITOR}" "${FILE}"
