#!/bin/bash

# SPDX-FileCopyrightText: 2017 - 2023 sudorook <daemon@nullcodon.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.

set -eu

ROOT="$(dirname "${0}")"

source "${ROOT}"/globals

if ! [[ -v entrydir ]] || [[ -z "${entrydir}" ]]; then
  show_error "entrydir missing in globals. Exiting."
  exit 3
fi

mkdir -p "${entrydir}"

FILE=${entrydir}/$(date -d '-6 hours' +%F).md

if ! [ -f "${FILE}" ]; then
  if ! [[ -v template ]] || [[ -z "${template}" ]]; then
    echo "# $(date -d '-6 hours' '+%A, %B %d, %Y')" >> "${FILE}"
    echo >> "${FILE}"
  elif ! [ -f "${template}" ]; then
    show_error "Template ${template} does not exist."
    exit 3
  else
    cat "${template}" >> "${FILE}"
    sed -i "s/@date@/$(date -d '-6 hours' '+%A, %B %d, %Y')/g" "${FILE}"
  fi
fi

eval "${EDITOR}" "${FILE}"
