#!/bin/bash

# SPDX-FileCopyrightText: 2024 - 2025 sudorook <daemon@nullcodon.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.

set -euo pipefail

ROOT="$(dirname "${0}")"

source "${ROOT}"/globals

! check_command grep realpath sed wslpath && exit 3

if sed -n "/\[interop\]/,/^\s*$/p" /etc/wsl.conf | grep -q "^enabled\ *=\ false"; then
  show_warning "This script requires Windows interop to be enabled in /etc/wsl.conf."
  exit 3
fi

case "${BROWSER}" in
  firefox)
    BROWSER_PATH="/mnt/c/Program Files/Mozilla Firefox/firefox.exe"
    ;;
  chrome)
    BROWSER_PATH="/mnt/c/Program Files/Google/Chrome/Application/chrome.exe"
    ;;
  *)
    show_error "${BROWSER@Q} not supported by this script. Exiting."
    exit 3
    ;;
esac

if ! [ -f "${BROWSER_PATH}" ]; then
  show_error "${BROWSER@Q} not found in host. Exiting."
  exit 3
fi

"${BROWSER_PATH}" "$(wslpath -w "$(realpath "${1}")")"
